// PROTOTYPE - throwaway. Generated by a scratch script (explorer4/gencss.mjs) from the class names in this folder:
// the dev server's stylesheet can lag behind new files, so round 4 ships its own copy of the utilities it uses.
export const GENERATED_CSS_4 = "@layer utilities;\n"
