version: "3.8"

services:
  mongo:
    image: mongo:7.0
    command: ["--replSet", "rs0", "--bind_ip_all", "--port", "27017"]
    ports:
      - 28017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=goodwatch
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASS}
    volumes:
      - "mongo_data:/data/db"
      - "mongo_config:/data/configdb"

volumes:
  mongo_data:
  mongo_config: