version: "3.8"

services:
  mongo:
    container_name: mongo
    hostname: mongo
    image: mongo:8
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ADMIN_PASS}
      - MONGO_INITDB_DATABASE=goodwatch
    ports:
      - "28017:28017"
    volumes:
      - mongodb:/data/db
      - ./mongodb-keyfile:/data/mongodb-keyfile
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"
    command: --replSet rs0 --bind_ip_all --port 28017 --keyFile /data/mongodb-keyfile

volumes:
  mongodb: