#!/bin/bash
cd "$(dirname "$0")"
P="Use your image generation tool. Edit this real photograph."
K="Preserve exactly: the camera angle and framing, the room, the lighting and color, the window, the lantern, the TV and its position, the TV sideboard, the floor, and every object not named here. The TV screen stays a uniformly flat, matte, pure #00FF00 green, evenly lit edge to edge. Photorealistic, honest and unstaged, real material textures, subtle film grain, everything sharp, no blur."
./run.sh dusk-ref.png fix1.png "$P Change ONLY the coffee table and what is on it: replace the large round table with a smaller, low, rectangular coffee table in dark smoked oak with visible grain and a slightly worn edge, about 40 cm high, clearly separated from the viewer's sofa and blanket by a visible strip of rug, its top a darker, cooler tone than the floor. On it, off-center: one small ceramic cup, about the size of a fist, near the far edge, and a Blu-ray case lying at a slight angle. They are minor details. $K"
[ -f fix1.png ] || exit 1
./run.sh fix1.png fix2.png "$P Change ONLY what is on the shelves and the picture on the right wall. Left shelves: a few paperbacks in mixed heights and colors, a row of about fifteen Blu-ray cases (thin cases, mixed spine colors, some leaning), a small ceramic bowl, a trailing pothos; exactly one small framed black-and-white photograph. Right shelves: a longer row of Blu-ray cases with gaps, a short horizontal stack, a small speaker, a snake plant. The right wall where the landscape print was is bare painted plaster. Spine titles are tiny and unreadable. $K"
[ -f fix2.png ] || exit 1
./run.sh fix2.png fix3.png "$P Change ONLY the sofa in the lower left and the blanket along the bottom: the sofa becomes a rust-colored linen sofa with visible seams, a slightly sagging seat cushion, and a cushion pushed into the corner; the blanket along the bottom edge becomes a moss-green chunky knit blanket, loosely draped with folds. $K"
