---
- name: Install Docker SDK for Python on all hosts
  hosts: all
  any_errors_fatal: true
  tasks:
    - name: Update apt package index
      ansible.builtin.apt:
        update_cache: yes
      changed_when: false

    - name: Pull latest git updates
      ansible.builtin.shell: git pull
      args:
        chdir: /root/goodwatch/goodwatch-monorepo/

- name: Stop and upgrade Windmill default workers on remote servers
  hosts: servers-default
  strategy: free
  any_errors_fatal: true
  tasks:
    - name: Pull latest images
      ansible.builtin.shell: docker compose pull
      args:
        chdir: /root/goodwatch/goodwatch-monorepo/goodwatch-remote/default/

    - name: Rebuild containers
      ansible.builtin.shell: docker compose build
      args:
        chdir: /root/goodwatch/goodwatch-monorepo/goodwatch-remote/default/

    - name: Stop docker compose
      ansible.builtin.shell: docker compose down
      args:
        chdir: /root/goodwatch/goodwatch-monorepo/goodwatch-remote/default/

- name: Stop and upgrade Windmill highperf workers on remote servers
  hosts: servers-highperf
  strategy: free
  any_errors_fatal: true
  tasks:
    - name: Pull latest images
      ansible.builtin.shell: docker compose pull
      args:
        chdir: /root/goodwatch/goodwatch-monorepo/goodwatch-remote/highperf/

    - name: Rebuild containers
      ansible.builtin.shell: docker compose build
      args:
        chdir: /root/goodwatch/goodwatch-monorepo/goodwatch-remote/highperf/

    - name: Stop docker compose
      ansible.builtin.shell: docker compose down
      args:
        chdir: /root/goodwatch/goodwatch-monorepo/goodwatch-remote/highperf/

- name: Stop and upgrade Windmill App on HQ
  hosts: local
  strategy: free
  any_errors_fatal: true
  tasks:
    - name: Pull latest images
      ansible.builtin.shell: docker compose pull
      args:
        chdir: /root/goodwatch/goodwatch-monorepo/goodwatch-hq/

    - name: Rebuild containers
      ansible.builtin.shell: docker compose build
      args:
        chdir: /root/goodwatch/goodwatch-monorepo/goodwatch-hq/

    - name: Stop docker compose
      ansible.builtin.shell: docker compose down
      args:
        chdir: /root/goodwatch/goodwatch-monorepo/goodwatch-hq/

- name: Run Windmill on HQ
  hosts: local
  any_errors_fatal: true
  tasks:
    - name: Start docker compose
      ansible.builtin.shell: docker compose up -d
      args:
        chdir: /root/goodwatch/goodwatch-monorepo/goodwatch-hq/

    - name: Wait for windmill service to be ready
      uri:
        url: https://windmill.goodwatch.app/api/version
        status_code: 200
      register: health_result
      until: health_result is success
      retries: 1000
      delay: 10

- name: Start Windmill default workers on remote servers once Windmill App is up and ready
  hosts: servers-default
  strategy: free
  any_errors_fatal: true
  tasks:
    - name: Start docker compose
      ansible.builtin.shell: docker compose up -d
      args:
        chdir: /root/goodwatch/goodwatch-monorepo/goodwatch-remote/default/

- name: Start Windmill highperf workers on remote servers once Windmill App is up and ready
  hosts: servers-highperf
  strategy: free
  any_errors_fatal: true
  tasks:
    - name: Start docker compose
      ansible.builtin.shell: docker compose up -d
      args:
        chdir: /root/goodwatch/goodwatch-monorepo/goodwatch-remote/highperf/
