SCHEMAS = {
    # ============================
    # ===== Core Lookups =====
    # ============================
    "age_certification": {
        "columns": {
            "certification_code": "TEXT",
            "country_code": "TEXT",
            "media_type": "TEXT CHECK (media_type IN ('movie','show'))",
            "meaning": "TEXT",
            "order_default": "INTEGER",
        },
        "primary_key": ["certification_code", "country_code", "media_type"],
        "shards": 2,
    },
    "country": {
        "columns": {
            "country_code": "TEXT",
            "english_name": "TEXT",
        },
        "primary_key": ["country_code"],
        "shards": 2,
    },
    "job": {
        "columns": {
            "job_title": "TEXT INDEX USING FULLTEXT",
            "department_name": "TEXT INDEX USING FULLTEXT",
        },
        "primary_key": ["job_title", "department_name"],
        "shards": 2,
    },
    "language": {
        "columns": {
            "language_code": "TEXT",
            "english_name": "TEXT",
            "native_name": "TEXT",
        },
        "primary_key": ["language_code"],
        "shards": 2,
    },
    "timezone": {
        "columns": {
            "country_code": "TEXT",
            "zones": "ARRAY(TEXT)",
        },
        "primary_key": ["country_code"],
        "shards": 2,
    },
    "genre": {
        "columns": {
            "tmdb_id": "INTEGER",
            "media_type": "TEXT CHECK (media_type IN ('movie','show'))",
            "name": "TEXT INDEX USING FULLTEXT",
        },
        "primary_key": ["tmdb_id", "media_type"],
        "shards": 2,
    },
    "streaming_service": {
        "columns": {
            "tmdb_id": "INTEGER",
            "media_type": "TEXT CHECK (media_type IN ('movie','show'))",
            "name": "TEXT INDEX USING FULLTEXT",
            "logo_path": "TEXT",
            "order_default": "INTEGER",
            "order_by_country": "OBJECT(DYNAMIC)",
        },
        "primary_key": ["tmdb_id", "media_type"],
        "shards": 2,
    },
    # ============================
    # ===== Movies and Shows =====
    # ============================
    "movie": {
        "columns": {
            "tmdb_id": "INTEGER",
            "title": "TEXT INDEX USING FULLTEXT",
            "original_title": "TEXT INDEX USING FULLTEXT",
            "tagline": "TEXT INDEX USING FULLTEXT",
            "synopsis": "TEXT INDEX USING FULLTEXT",
            "popularity": "DOUBLE",
            "status": "TEXT",
            "adult": "BOOLEAN",
            "poster_path": "TEXT",
            "backdrop_path": "TEXT",
            "release_year": "INTEGER",
            "release_date": "TIMESTAMP",
            "movie_series_id": "INTEGER",
            "runtime": "INTEGER",
            "budget": "BIGINT",
            "revenue": "BIGINT",
            "age_certifications": "ARRAY(TEXT)",
            "genres": "ARRAY(TEXT)",
            "keywords": "ARRAY(TEXT)",
            "tropes": "ARRAY(TEXT)",
            "homepage": "TEXT",
            "imdb_id": "TEXT",
            "wikidata_id": "TEXT",
            "facebook_id": "TEXT",
            "instagram_id": "TEXT",
            "twitter_id": "TEXT",
            "production_company_ids": "ARRAY(INTEGER)",
            "production_country_codes": "ARRAY(TEXT)",
            "origin_country_codes": "ARRAY(TEXT)",
            "original_language_code": "TEXT",
            "spoken_language_codes": "ARRAY(TEXT)",
            "is_anime": "BOOLEAN",
            "production_method": "TEXT",
            "animation_style": "TEXT",
            "tmdb_url": "TEXT",
            "tmdb_user_score_original": "DOUBLE",
            "tmdb_user_score_normalized_percent": "DOUBLE",
            "tmdb_user_score_rating_count": "INTEGER",
            "imdb_url": "TEXT",
            "imdb_user_score_original": "DOUBLE",
            "imdb_user_score_normalized_percent": "DOUBLE",
            "imdb_user_score_rating_count": "INTEGER",
            "metacritic_url": "TEXT",
            "metacritic_user_score_original": "DOUBLE",
            "metacritic_user_score_normalized_percent": "DOUBLE",
            "metacritic_user_score_rating_count": "INTEGER",
            "metacritic_meta_score_original": "DOUBLE",
            "metacritic_meta_score_normalized_percent": "DOUBLE",
            "metacritic_meta_score_review_count": "INTEGER",
            "rotten_tomatoes_url": "TEXT",
            "rotten_tomatoes_audience_score_original": "DOUBLE",
            "rotten_tomatoes_audience_score_normalized_percent": "DOUBLE",
            "rotten_tomatoes_audience_score_rating_count": "INTEGER",
            "rotten_tomatoes_tomato_score_original": "DOUBLE",
            "rotten_tomatoes_tomato_score_normalized_percent": "DOUBLE",
            "rotten_tomatoes_tomato_score_review_count": "INTEGER",
            "goodwatch_user_score_normalized_percent": "DOUBLE",
            "goodwatch_user_score_rating_count": "INTEGER",
            "goodwatch_official_score_normalized_percent": "DOUBLE",
            "goodwatch_official_score_review_count": "INTEGER",
            "goodwatch_overall_score_normalized_percent": "DOUBLE",
            "goodwatch_overall_score_voting_count": "INTEGER",
            "streaming_country_codes": "ARRAY(TEXT)",
            "streaming_service_ids": "ARRAY(INTEGER)",
            "streaming_availabilities": "ARRAY(TEXT)",
            "tmdb_recommendation_ids": "ARRAY(INTEGER)",
            "tmdb_similar_ids": "ARRAY(INTEGER)",
            "essence_text": "TEXT INDEX USING FULLTEXT",
            "essence_tags": "ARRAY(TEXT)",
            "fingerprint_scores": "OBJECT(DYNAMIC)",
            "fingerprint_highlight_keys": "ARRAY(TEXT)",
            "content_advisories": "ARRAY(TEXT)",
            "suitability_solo_watch": "BOOLEAN",
            "suitability_date_night": "BOOLEAN",
            "suitability_group_party": "BOOLEAN",
            "suitability_family": "BOOLEAN",
            "suitability_partner": "BOOLEAN",
            "suitability_friends": "BOOLEAN",
            "suitability_kids": "BOOLEAN",
            "suitability_teens": "BOOLEAN",
            "suitability_adults": "BOOLEAN",
            "suitability_intergenerational": "BOOLEAN",
            "suitability_public_viewing_safe": "BOOLEAN",
            "context_is_thought_provoking": "BOOLEAN",
            "context_is_pure_escapism": "BOOLEAN",
            "context_is_background_friendly": "BOOLEAN",
            "context_is_comfort_watch": "BOOLEAN",
            "context_is_binge_friendly": "BOOLEAN",
            "context_is_drop_in_friendly": "BOOLEAN",
            "tmdb_details_created_at": "TIMESTAMP",
            "tmdb_details_updated_at": "TIMESTAMP",
            "tmdb_providers_created_at": "TIMESTAMP",
            "tmdb_providers_updated_at": "TIMESTAMP",
            "imdb_ratings_created_at": "TIMESTAMP",
            "imdb_ratings_updated_at": "TIMESTAMP",
            "metacritic_ratings_created_at": "TIMESTAMP",
            "metacritic_ratings_updated_at": "TIMESTAMP",
            "rotten_tomatoes_ratings_created_at": "TIMESTAMP",
            "rotten_tomatoes_ratings_updated_at": "TIMESTAMP",
            "tvtropes_tags_created_at": "TIMESTAMP",
            "tvtropes_tags_updated_at": "TIMESTAMP",
            "dna_created_at": "TIMESTAMP",
            "dna_updated_at": "TIMESTAMP",
        },
        "primary_key": ["tmdb_id"],
        "shards": 12,
    },
    "show": {
        "columns": {
            "tmdb_id": "INTEGER",
            "title": "TEXT INDEX USING FULLTEXT",
            "original_title": "TEXT INDEX USING FULLTEXT",
            "tagline": "TEXT INDEX USING FULLTEXT",
            "synopsis": "TEXT INDEX USING FULLTEXT",
            "popularity": "DOUBLE",
            "status": "TEXT",
            "adult": "BOOLEAN",
            "poster_path": "TEXT",
            "backdrop_path": "TEXT",
            "release_year": "INTEGER",
            "first_air_date": "TIMESTAMP",
            "last_air_date": "TIMESTAMP",
            "number_of_seasons": "INTEGER",
            "number_of_episodes": "INTEGER",
            "episode_runtime": "ARRAY(INTEGER)",
            "in_production": "BOOLEAN",
            "budget": "BIGINT",
            "revenue": "BIGINT",
            "age_certifications": "ARRAY(TEXT)",
            "genres": "ARRAY(TEXT)",
            "keywords": "ARRAY(TEXT)",
            "tropes": "ARRAY(TEXT)",
            "homepage": "TEXT",
            "imdb_id": "TEXT",
            "wikidata_id": "TEXT",
            "facebook_id": "TEXT",
            "instagram_id": "TEXT",
            "twitter_id": "TEXT",
            "production_company_ids": "ARRAY(INTEGER)",
            "network_ids": "ARRAY(INTEGER)",
            "production_country_codes": "ARRAY(TEXT)",
            "origin_country_codes": "ARRAY(TEXT)",
            "original_language_code": "TEXT",
            "spoken_language_codes": "ARRAY(TEXT)",
            "is_anime": "BOOLEAN",
            "production_method": "TEXT",
            "animation_style": "TEXT",
            "tmdb_url": "TEXT",
            "tmdb_user_score_original": "DOUBLE",
            "tmdb_user_score_normalized_percent": "DOUBLE",
            "tmdb_user_score_rating_count": "INTEGER",
            "imdb_url": "TEXT",
            "imdb_user_score_original": "DOUBLE",
            "imdb_user_score_normalized_percent": "DOUBLE",
            "imdb_user_score_rating_count": "INTEGER",
            "metacritic_url": "TEXT",
            "metacritic_user_score_original": "DOUBLE",
            "metacritic_user_score_normalized_percent": "DOUBLE",
            "metacritic_user_score_rating_count": "INTEGER",
            "metacritic_meta_score_original": "DOUBLE",
            "metacritic_meta_score_normalized_percent": "DOUBLE",
            "metacritic_meta_score_review_count": "INTEGER",
            "rotten_tomatoes_url": "TEXT",
            "rotten_tomatoes_audience_score_original": "DOUBLE",
            "rotten_tomatoes_audience_score_normalized_percent": "DOUBLE",
            "rotten_tomatoes_audience_score_rating_count": "INTEGER",
            "rotten_tomatoes_tomato_score_original": "DOUBLE",
            "rotten_tomatoes_tomato_score_normalized_percent": "DOUBLE",
            "rotten_tomatoes_tomato_score_review_count": "INTEGER",
            "goodwatch_user_score_normalized_percent": "DOUBLE",
            "goodwatch_user_score_rating_count": "INTEGER",
            "goodwatch_official_score_normalized_percent": "DOUBLE",
            "goodwatch_official_score_review_count": "INTEGER",
            "goodwatch_overall_score_normalized_percent": "DOUBLE",
            "goodwatch_overall_score_voting_count": "INTEGER",
            "streaming_country_codes": "ARRAY(TEXT)",
            "streaming_service_ids": "ARRAY(INTEGER)",
            "streaming_availabilities": "ARRAY(TEXT)",
            "tmdb_recommendation_ids": "ARRAY(INTEGER)",
            "tmdb_similar_ids": "ARRAY(INTEGER)",
            "essence_text": "TEXT INDEX USING FULLTEXT",
            "essence_tags": "ARRAY(TEXT)",
            "fingerprint_scores": "OBJECT(DYNAMIC)",
            "fingerprint_highlight_keys": "ARRAY(TEXT)",
            "content_advisories": "ARRAY(TEXT)",
            "suitability_solo_watch": "BOOLEAN",
            "suitability_date_night": "BOOLEAN",
            "suitability_group_party": "BOOLEAN",
            "suitability_family": "BOOLEAN",
            "suitability_partner": "BOOLEAN",
            "suitability_friends": "BOOLEAN",
            "suitability_kids": "BOOLEAN",
            "suitability_teens": "BOOLEAN",
            "suitability_adults": "BOOLEAN",
            "suitability_intergenerational": "BOOLEAN",
            "suitability_public_viewing_safe": "BOOLEAN",
            "context_is_thought_provoking": "BOOLEAN",
            "context_is_pure_escapism": "BOOLEAN",
            "context_is_background_friendly": "BOOLEAN",
            "context_is_comfort_watch": "BOOLEAN",
            "context_is_binge_friendly": "BOOLEAN",
            "context_is_drop_in_friendly": "BOOLEAN",
            "tmdb_details_created_at": "TIMESTAMP",
            "tmdb_details_updated_at": "TIMESTAMP",
            "tmdb_providers_created_at": "TIMESTAMP",
            "tmdb_providers_updated_at": "TIMESTAMP",
            "imdb_ratings_created_at": "TIMESTAMP",
            "imdb_ratings_updated_at": "TIMESTAMP",
            "metacritic_ratings_created_at": "TIMESTAMP",
            "metacritic_ratings_updated_at": "TIMESTAMP",
            "rotten_tomatoes_ratings_created_at": "TIMESTAMP",
            "rotten_tomatoes_ratings_updated_at": "TIMESTAMP",
            "tvtropes_tags_created_at": "TIMESTAMP",
            "tvtropes_tags_updated_at": "TIMESTAMP",
            "dna_created_at": "TIMESTAMP",
            "dna_updated_at": "TIMESTAMP",
        },
        "primary_key": ["tmdb_id"],
        "shards": 12,
    },
    "movie_series": {
        "columns": {
            "tmdb_id": "INTEGER",
            "name": "TEXT INDEX USING FULLTEXT",
            "poster_path": "TEXT",
            "backdrop_path": "TEXT",
        },
        "primary_key": ["tmdb_id"],
        "shards": 3,
    },
    "season": {
        "columns": {
            "tmdb_id": "INTEGER",
            "show_id": "INTEGER",
            "name": "TEXT INDEX USING FULLTEXT",
            "season_number": "INTEGER",
            "air_date": "TIMESTAMP",
            "episode_count": "INTEGER",
            "overview": "TEXT INDEX USING FULLTEXT",
            "poster_path": "TEXT",
            "vote_average": "DOUBLE",
        },
        "primary_key": ["tmdb_id"],
        "shards": 12,
    },
    # ============================
    # ===== Related Metadata =====
    # ============================
    "media_image": {
        "columns": {
            "media_tmdb_id": "INTEGER",
            "media_type": "TEXT CHECK (media_type IN ('movie','show'))",
            "image_type": "TEXT",
            "url_path": "TEXT",
            "language_code": "TEXT",
            "aspect_ratio": "DOUBLE",
            "width": "INTEGER",
            "height": "INTEGER",
            "tmdb_vote_average": "DOUBLE",
            "tmdb_vote_count": "INTEGER",
        },
        "primary_key": [
            "media_tmdb_id",
            "media_type",
            "image_type",
            "url_path",
            "language_code",
        ],
        "shards": 12,
    },
    "media_video": {
        "columns": {
            "media_tmdb_id": "INTEGER",
            "media_type": "TEXT CHECK (media_type IN ('movie','show'))",
            "tmdb_id": "TEXT",
            "video_type": "TEXT",
            "site": "TEXT",
            "site_key": "TEXT",
            "language_code": "TEXT",
            "country_code": "TEXT",
            "name": "TEXT",
            "size": "INTEGER",
            "official": "BOOLEAN",
            "published_at": "TIMESTAMP",
        },
        "primary_key": ["media_tmdb_id", "media_type", "tmdb_id"],
        "shards": 12,
    },
    "trope": {
        "columns": {
            "media_tmdb_id": "INTEGER",
            "media_type": "TEXT CHECK (media_type IN ('movie','show'))",
            "name": "TEXT INDEX USING FULLTEXT",
            "url": "TEXT",
            "content": "TEXT INDEX USING FULLTEXT",
        },
        "primary_key": ["media_tmdb_id", "media_type", "name"],
        "shards": 3,
    },
    "alternative_title": {
        "columns": {
            "media_tmdb_id": "INTEGER",
            "media_type": "TEXT CHECK (media_type IN ('movie','show'))",
            "country_code": "TEXT",
            "title": "TEXT INDEX USING FULLTEXT",
        },
        "primary_key": ["media_tmdb_id", "media_type", "country_code"],
        "shards": 6,
    },
    "translation": {
        "columns": {
            "media_tmdb_id": "INTEGER",
            "media_type": "TEXT CHECK (media_type IN ('movie','show'))",
            "language_code": "TEXT",
            "country_code": "TEXT",
            "name": "TEXT",
            "english_name": "TEXT",
            "title": "TEXT INDEX USING FULLTEXT",
            "overview": "TEXT INDEX USING FULLTEXT",
            "tagline": "TEXT",
            "homepage": "TEXT",
            "runtime": "INTEGER",
        },
        "primary_key": ["media_tmdb_id", "media_type", "language_code", "country_code"],
        "shards": 6,
    },
    "release_event": {
        "columns": {
            "media_tmdb_id": "INTEGER",
            "media_type": "TEXT CHECK (media_type IN ('movie','show'))",
            "country_code": "TEXT",
            "release_type": "INTEGER",
            "release_date": "TIMESTAMP",
            "certification": "TEXT",
            "note": "TEXT",
            "descriptors": "ARRAY(TEXT)",
        },
        "primary_key": [
            "media_tmdb_id",
            "media_type",
            "country_code",
            "release_date",
            "release_type",
            "certification",
        ],
        "shards": 6,
    },
    "production_company": {
        "columns": {
            "tmdb_id": "INTEGER",
            "name": "TEXT INDEX USING FULLTEXT",
            "logo_path": "TEXT",
            "origin_country": "TEXT",
        },
        "primary_key": ["tmdb_id"],
        "shards": 2,
    },
    "network": {
        "columns": {
            "tmdb_id": "INTEGER",
            "name": "TEXT INDEX USING FULLTEXT",
            "logo_path": "TEXT",
            "origin_country": "TEXT",
        },
        "primary_key": ["tmdb_id"],
        "shards": 2,
    },
    "person": {
        "columns": {
            "tmdb_id": "INTEGER",
            "name": "TEXT INDEX USING FULLTEXT",
            "original_name": "TEXT",
            "profile_path": "TEXT",
            "popularity": "DOUBLE",
            "adult": "BOOLEAN",
            "gender": "INTEGER",
            "known_for_department": "TEXT",
        },
        "primary_key": ["tmdb_id"],
        "shards": 6,
    },
    "person_appeared_in": {
        "columns": {
            "media_tmdb_id": "INTEGER",
            "media_type": "TEXT CHECK (media_type IN ('movie','show'))",
            "person_tmdb_id": "INTEGER",
            "credit_id": "TEXT",
            "character": "TEXT",
            "order_default": "INTEGER",
            "episode_count_character": "INTEGER",
            "episode_count_total": "INTEGER",
        },
        "primary_key": ["media_tmdb_id", "media_type", "person_tmdb_id", "credit_id"],
        "shards": 6,
    },
    "person_worked_on": {
        "columns": {
            "media_tmdb_id": "INTEGER",
            "media_type": "TEXT CHECK (media_type IN ('movie','show'))",
            "person_tmdb_id": "INTEGER",
            "credit_id": "TEXT",
            "job": "TEXT",
            "department": "TEXT",
            "episode_count_job": "INTEGER",
            "episode_count_total": "INTEGER",
        },
        "primary_key": ["media_tmdb_id", "media_type", "person_tmdb_id", "credit_id"],
        "shards": 6,
    },
    "streaming_availability": {
        "columns": {
            "media_tmdb_id": "INTEGER",
            "media_type": "TEXT CHECK (media_type IN ('movie','show'))",
            "country_code": "TEXT",
            "streaming_type": "TEXT",
            "streaming_service_id": "INTEGER",
            "display_priority": "INTEGER",
            "tmdb_link": "TEXT",
            "stream_url": "TEXT",
            "price_dollar": "DOUBLE",
            "quality": "TEXT",
        },
        "primary_key": [
            "media_tmdb_id",
            "media_type",
            "country_code",
            "streaming_service_id",
            "streaming_type",
        ],
        "shards": 12,
    },
    # ============================
    # ===== User Data ============
    # ============================
    "user_setting": {
        "columns": {
            "user_id": "TEXT",
            "key": "TEXT",
            "value": "TEXT",
        },
        "primary_key": ["user_id", "key"],
        "shards": 3,
    },
    "user_skipped": {
        "columns": {
            "user_id": "TEXT",
            "tmdb_id": "INTEGER",
            "media_type": "TEXT CHECK (media_type IN ('movie','show'))",
        },
        "primary_key": ["user_id", "tmdb_id", "media_type"],
        "shards": 3,
    },
    "user_wishlist": {
        "columns": {
            "user_id": "TEXT",
            "tmdb_id": "INTEGER",
            "media_type": "TEXT CHECK (media_type IN ('movie','show'))",
        },
        "primary_key": ["user_id", "tmdb_id", "media_type"],
        "shards": 6,
    },
    "user_score": {
        "columns": {
            "user_id": "TEXT",
            "tmdb_id": "INTEGER",
            "media_type": "TEXT CHECK (media_type IN ('movie','show'))",
            "score": "INTEGER",
            "review": "TEXT",
        },
        "primary_key": ["user_id", "tmdb_id", "media_type"],
        "shards": 6,
    },
    "user_favorite": {
        "columns": {
            "user_id": "TEXT",
            "tmdb_id": "INTEGER",
            "media_type": "TEXT CHECK (media_type IN ('movie','show'))",
        },
        "primary_key": ["user_id", "tmdb_id", "media_type"],
        "shards": 3,
    },
    "user_watch_history": {
        "columns": {
            "user_id": "TEXT",
            "tmdb_id": "INTEGER",
            "media_type": "TEXT CHECK (media_type IN ('movie','show'))",
            # multi watch
            "watched_at_list": "ARRAY(TIMESTAMP)",
            # “current watch” state for this title
            "progress_percent": "DOUBLE",
            "progress_seconds": "INTEGER",
            "season_number": "INTEGER",
            "episode_number": "INTEGER",
            "ingest_source": "TEXT",
            # convenience denorms
            "first_watched_at": "TIMESTAMP",
            "last_watched_at": "TIMESTAMP",
            "watch_count": "INTEGER",
        },
        "primary_key": ["user_id", "tmdb_id", "media_type"],
        "shards": 6,
    },
}


def main():
    pass
