services:
  arangodb:
    image: arangodb/arangodb:${ARANGO_VERSION}
    container_name: arango_node
    restart: always
    mem_limit: 23g
    memswap_limit: 23g
    ports:
      - "${SELF_IP}:8528:8528"  # Arango Starter
      - "${SELF_IP}:8529:8529"  # UI and for your applications
      - "${SELF_IP}:8530:8530"  # DBServer communication
      - "${SELF_IP}:8531:8531"  # Agent communication
      - "${SELF_IP}:9101:9101"  # Prometheus
    volumes:
      - arango_data:/data
      - ./jwtsecret:/jwtsecret:ro
    environment:
      - ARANGO_LICENSE_KEY=accept
      - ARANGO_ROOT_PASSWORD=${ARANGO_ROOT_PASSWORD}
    command: >
      arangodb
      --starter.data-dir=/data
      --starter.address=${SELF_IP}
      --starter.join=${STARTER_JOIN}
      --auth.jwt-secret=/jwtsecret
      
      --server.storage-engine=rocksdb
      --all.log.level=INFO
      --all.tcp.reuse-address=true

      --dbservers.rocksdb.block-cache-size=11g
      --dbservers.experimental-vector-index=true
      --coordinators.experimental-vector-index=true

volumes:
  arango_data: