[project]
name = ""
version = ""
description = ""
authors = [
    {name = "Alper Ortac", email = "alportac@gmail.com"},
]
dependencies = [
    "wmill>=1.181.0",
    "pymongo>=4.5.0",
    "mongoengine>=0.27.0",
]
requires-python = ">=3.10"
readme = "README.md"
license = {text = "MIT"}

