[project]
name = "webapp-scripts"
version = "0.1.0"
description = ""
authors = [{name = "Alper Ortac", email = "alportac@gmail.com"}]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "python-dotenv>=1.0.1",
    "crate>=0.35.2",
]
