// Short phrases for fingerprint attributes, as they read inside a sentence: "Real scares and a slow burn". Used for
// what sets an island apart and for a card's why line.
import type { CoreScores } from "~/server/utils/fingerprint"
import { getFingerprintMeta } from "~/ui/fingerprint/fingerprintMeta"

const PHRASES: Record<keyof CoreScores, string> = {
	adrenaline: "adrenaline",
	tension: "suspense",
	scare: "real scares",
	violence: "hard-edged violence",
	romance: "romance",
	eroticism: "sensuality",
	wholesome: "wholesome warmth",
	wonder: "a sense of wonder",
	pathos: "deeply moving stories",
	melancholy: "melancholy",
	uncanny: "the uncanny",
	catharsis: "a cathartic payoff",
	nostalgia: "nostalgia",
	situational_comedy: "comic situations",
	wit_wordplay: "wit and wordplay",
	physical_comedy: "slapstick",
	cringe_humor: "awkward humor",
	absurdist_humor: "absurd humor",
	satire_parody: "satire and parody",
	dark_humor: "dark humor",
	fantasy: "fantasy worlds",
	futuristic: "science fiction and future societies",
	historical: "period pieces",
	contemporary_realism: "grounded realism",
	crime: "crime",
	mystery: "a mystery to crack",
	warfare: "war stories",
	political: "politics",
	sports: "sports",
	biographical: "real people’s lives",
	coming_of_age: "coming-of-age",
	family_dynamics: "family relationships",
	psychological: "inner struggles and perception",
	showbiz: "showbiz",
	gaming: "games",
	pop_culture: "pop culture",
	social_commentary: "social critique",
	class_and_capitalism: "class and money",
	technology_and_humanity: "tech and what it does to us",
	spiritual: "the spiritual",
	narrative_structure: "well-constructed stories",
	dialogue_quality: "well-written dialogue",
	character_depth: "nuanced characters",
	slow_burn: "a slow burn",
	fast_pace: "breakneck pace",
	intrigue: "intrigue",
	complexity: "complexity",
	rewatchability: "stories that reward repeat viewing",
	hopefulness: "hope",
	bleakness: "a bleak outlook",
	ambiguity: "open interpretations",
	novelty: "the unexpected",
	homage_and_reference: "tributes to other works",
	non_linear_narrative: "nonlinear storytelling",
	meta_narrative: "self-aware storytelling",
	surrealism: "the surreal",
	eccentricity: "eccentrics",
	philosophical: "big questions",
	educational: "learning something",
	direction: "a strong director's hand",
	acting: "great performances",
	cinematography: "striking images",
	editing: "precise editing",
	music_composition: "a great score",
	world_immersion: "worlds to get lost in",
	spectacle: "spectacle",
	visual_stylization: "distinctive visual style",
	pastiche: "imitations of other artistic styles",
	psychedelic: "the psychedelic",
	grotesque: "the grotesque",
	camp_and_irony: "camp",
	dialogue_centrality: "stories carried by conversation",
	music_centrality: "stories shaped by their soundtrack",
	sound_centrality: "stories shaped by sound design",
}

export const phraseOf = (key: string): string =>
	PHRASES[key as keyof CoreScores] ??
	getFingerprintMeta(key).label.toLowerCase()

/** "real scares", "a slow burn" -> "Real scares and a slow burn". */
export function sentence(parts: string[]): string {
	const text = parts.filter(Boolean).join(" and ")
	return text.charAt(0).toUpperCase() + text.slice(1)
}
