// PROTOTYPE (issue #368). What running the scenarios turned up: every place where the settled rules give a
// result a member would find odd, disagree with each other, or say nothing. The report prints this list first.

export interface Surprise {
	kind: "contradiction" | "odd" | "undefined"
	title: string
	/** The recommendation in a few words, for the overview table. */
	short: string
	/** Keys of the scenarios that show it. */
	scenarios: string[]
	what: string
	options: string[]
	recommended: string
	inPrototype: string
}

export const SURPRISES: Surprise[] = [
	{
		kind: "contradiction",
		title: "Pressing Seen on a show whose season is still airing does not make it Seen",
		short: "Keep the definition. On an airing show the press gives Watching, caught up",
		scenarios: ["seen-press-while-airing", "no-air-date", "rated-without-episodes"],
		what: "The glossary says a show is Seen when it is watched through with no season still airing, and that caught up mid-season stays Watching. The map says Seen on a show marks every aired regular episode. Together: the member presses a button called Seen and gets a show that is Watching and caught up, not Seen. A show whose only season never ends (a daily show, or one season since 2010) can never be Seen by watching at all, only by a rating.",
		options: [
			"The press gives Watching and caught up while a season airs. The show turns Seen by itself when the season is over. The button has to say what it did, for example \"Marked 6 episodes, caught up\".",
			"The press always makes the show Seen, like a rating does. Then a member who follows a weekly show and presses Seen once has a Seen show with new episodes every week, and it is never in Watching unless they mark an episode by hand.",
			"Seen is not offered while a season airs; the episode list offers \"mark all aired\" in its place.",
		],
		recommended: "The first. It keeps the one definition of Seen, and the member who presses Seen mid-season means \"I am up to date\", which is what Watching and caught up says. The undo is the same press again: it removes the watches the press made.",
		inPrototype: "`seenPressWhileAiring: \"caught-up\"`, a proposal. The second table of the scenario runs `\"seen\"`.",
	},
	{
		kind: "contradiction",
		title: "Removing Seen can leave the show Seen",
		short: "Offer Remove Seen only when it removes something, and say why otherwise",
		scenarios: ["remove-seen-changes-nothing", "rated-without-episodes"],
		what: "Removing Seen removes only bulk watches. A show the member watched episode by episode, or imported, has none, so it is still watched through and still Seen after the press. A rated show is Seen because of the rating, so it stays Seen as well. In both cases the button does nothing the member can see.",
		options: [
			"Remove Seen is offered only when the show has watches that a Seen press made. Otherwise the interface says why the show is Seen (\"every episode is marked\", \"you rated it\") and leads to the episode list or the rating.",
			"Remove Seen removes every watch of the show, and the rating. It always works, and it deletes dated watches and a rating in one press.",
			"Leave it: the press removes what it can.",
		],
		recommended: "The first. A press must never delete dated watches or a rating as a side effect, and it must not look broken either.",
		inPrototype: "The press is always accepted and removes the bulk watches it finds; the scenario shows it changing nothing. `view().seen` plus the origin of the watches is enough to decide what to offer.",
	},
	{
		kind: "odd",
		title: "Removing Seen also removes seasons the member marked earlier",
		short: "Remove only the watches the Seen press made",
		scenarios: ["remove-seen-with-hand-marks"],
		what: "ADR 0008 gives a watch one of three origins: by hand, in bulk \"by marking a whole show or season\", or imported. Mark season and mark up to here make bulk watches too. A member who marked season 1 as a season, later pressed Seen and then removes Seen loses season 1 as well: 14 watches go, 2 stay. They expected to be back where they were before the press, at 8 of 16.",
		options: [
			"Every bulk watch goes, as the map's sentence reads.",
			"A bulk watch records which action made it (Seen on the show, a season, up to here). Removing Seen removes only Seen's own. Removing a season's mark removes only that season's.",
			"Each bulk action gets its own id, like an import, so one press can be undone exactly even after two Seen presses.",
		],
		recommended: "The second. It is one more value in a column the ADR already has, and it makes Remove Seen the exact undo of Seen.",
		inPrototype: "`removeSeenRemoves: \"all-bulk\"` as the map reads. The second table runs `\"show-bulk\"`. The watch's origin already carries the bulk action.",
	},
	{
		kind: "contradiction",
		title: "A re-added episode undoes progress under ADR 0008",
		short: "Count the watch for the one listed episode with the same season and number",
		scenarios: [
			"tmdb-readds-episode-watching",
			"tmdb-readds-episode-seen",
			"tmdb-renumbers",
		],
		what: "TMDB can delete an episode and add it again under a new id. ADR 0008 keeps the old watch and doesn't count it. On a Watching show the member drops from caught up to one behind, and because the next episode is the earliest unwatched one, the Watching view offers S1E2 to a member who is in season 2. On a Seen show the show stays Seen with 3 of 4 watched and a next episode. While the episode is only removed, nothing looks wrong: progress goes from 11 of 11 to 10 of 10. The alternative has its own wrong case: when an editor deletes a duplicate and renumbers the episodes after it, the orphaned watch lands on a different episode, and the member's next episode skips one.",
		options: [
			"ADR 0008 as written: the watch never counts again. Every delete and re-add by an editor costs every member one episode, silently.",
			"Count the watch when exactly one listed episode has the same season and number. Fixes the re-add. Marks one wrong episode in the renumbering case.",
			"The same, and while the removed episode's row is still stored (the research keeps it 180 days), also require the same air date. That separates a re-add (same date) from a renumbering (another episode's date).",
		],
		recommended: "The third if the catalog keeps removed rows as the research proposes, otherwise the second. A wrong mark on one episode in a rare renumbering is cheaper than lost progress on every re-add. Decide the match when reading, and leave the stored watch as it is, so a later correction by TMDB costs nothing.",
		inPrototype: "`goneEpisode: \"never-counts\"` as the ADR says. The second tables run `\"same-number\"`. The air-date check is not built.",
	},
	{
		kind: "odd",
		title: "Whether a show is Seen depends on when somebody last looked",
		short: "Work Seen out from the watches and the air dates, not from the moment of the check",
		scenarios: [
			"season-ends-looked-at",
			"season-ends-not-looked-at",
			"import-old-history",
		],
		what: "\"Watched through with no season still airing\" becomes true on a day when nobody does anything: the 45 days run out. A show stays Seen when later episodes air, so the result has to be written down at that moment. Two members with the same watches then differ: the one whose show was recomputed between the seasons has a Seen show with new episodes and no status; the one whose show was not has a Watching show five episodes behind. An import shows the same thing from the other side: a season watched in 2019, imported today, is Watching and eight behind, although the member finished the show as it stood then.",
		options: [
			"Decide when the show is recomputed, and recompute it on a schedule (the daily catalog refresh touches every show with a new episode). The answer still depends on the job having run in the gap.",
			"Work it out from the data: the show is Seen since the first day on which every regular episode aired by then had a watch known by then and no season was airing. A watch is known from its date, or from when its row was written if it has none. Same data, same answer, whenever it is asked.",
			"Never by the calendar: a show becomes Seen by watching only at the moment of a watch, a press or a rating. Then a show whose finale is not marked never becomes Seen by watching.",
		],
		recommended: "The second. It needs the next surprise's change as well, because with today's episode list a season that started later looks like a season still airing on any earlier day.",
		inPrototype: "`seenEvaluation: \"when-looked-at\"`, which is the plain reading and not the recommendation. The second tables run `\"from-history\"` together with `upcomingSeason: \"not-airing\"`.",
	},
	{
		kind: "odd",
		title: "An announced premiere keeps a finished show \"still airing\" for months",
		short: "A season nothing has aired of is not airing",
		scenarios: ["upcoming-season-listed-first", "upcoming-season-listed-after"],
		what: "The research judges the highest regular season that has an aired or dated episode. TMDB lists a premiere as soon as it is announced, sometimes a year ahead. A member who finishes season 2 after that date appeared is Watching and caught up for eleven months, gets no prompt to rate, and the show sits in the Watching views with nothing to watch. A member who finished one day before the date appeared has a Seen show. Same episodes, same watches.",
		options: [
			"As the research has it.",
			"A season is judged only once one of its episodes has aired. Until then the season before it decides, and that one ended with its finale.",
			"The same with a short lead: a season counts as airing from 7 days before its premiere.",
		],
		recommended: "The second. \"Still airing\" then means what the words say, and the order of TMDB's edit and the member's last watch no longer matters.",
		inPrototype: "`upcomingSeason: \"airing\"` as the research reads. The second table runs `\"not-airing\"`.",
	},
	{
		kind: "odd",
		title: "A break longer than 45 days turns a show Seen in the middle of its season",
		short: "A later episode of a season the member has watched from puts the show back to Watching",
		scenarios: ["weekly-network", "split-season", "canceled-with-episodes-left"],
		what: "A weekly network season has no finale mark and is listed three or four weeks ahead. When nothing is listed for 45 days (a winter break, a strike, the gap before part two) the season counts as over. A caught-up member's show turns Seen, loses its status, and the prompt to rate appears mid-season. When the next episode airs the show is \"Seen, new episodes\" with no status, and by the map it stays Seen. The opposite also holds: after a real finale that TMDB has not marked, the member waits 45 days for Seen and for the prompt.",
		options: [
			"A longer gap, for example 120 days. Fewer false endings, and every unmarked real ending takes four months to turn Seen.",
			"Keep 45 days, and let a later episode of a season the member has already watched from reopen the show: it is Watching again and not Seen. A new season still leaves the show Seen, which is what the map's sentence is about.",
			"Keep everything, and have the Watching views treat \"Seen, new episodes\" like Watching. The state stays odd and every view has to know about it.",
		],
		recommended: "The second. It repairs the false ending when it shows, whatever its cause: a break, a split season, a burn-off after a cancellation. It narrows the map's \"stays Seen when later episodes air\" to later seasons, so it needs the owner's yes.",
		inPrototype: "`laterEpisodes: \"stay-seen\"` as the map says. The second tables of the weekly and the split-season scenario run `\"reopen\"`.",
	},
	{
		kind: "odd",
		title: "The mid-season mark changes nothing",
		short: "Covered by the reopen rule; a longer gap after a mid-season episode is optional",
		scenarios: ["split-season"],
		what: "TMDB marks the last episode before a break inside a season as `mid_season`. It is the one case where the data says \"this season is not over\". The research's rule treats it like any other episode, so 46 days into the break the show is Seen and the prompt to rate appears.",
		options: [
			"No special case; the reopen rule of the surprise before this one repairs it when part two airs.",
			"A longer gap when the last aired episode is `mid_season`, for example a year. The show stays Watching and caught up through the break.",
		],
		recommended: "Both. The second is a small change that avoids the wrong Seen and the wrong prompt in the first place, for the seasons TMDB marks; the first covers the rest.",
		inPrototype: "`midSeasonGapDays: 45`, no difference, as the research reads. Set it to 365 to try the second option.",
	},
	{
		kind: "odd",
		title: "One episode without a date keeps a season airing forever",
		short: "An episode without a date does not keep a season airing",
		scenarios: ["no-air-date"],
		what: "An episode without a date has not aired. By the research's first clause a season that lists an episode which has not aired is still airing. TMDB has blank episodes in old seasons (68 of 4,743 sampled had no date). A show with one of them can never be Seen by watching: the member is Watching and caught up for good, until TMDB sets the show to Ended.",
		options: [
			"As the research has it.",
			"Only an episode dated in the future keeps a season airing. An episode without a date falls under the 45 days like a season with nothing listed ahead.",
		],
		recommended: "The second.",
		inPrototype: "`undatedEpisode: \"keeps-airing\"` as the research reads. The second table runs `\"ignored\"`.",
	},
	{
		kind: "odd",
		title: "Ended or Canceled closes a season that still has episodes to air",
		short: "A dated episode ahead keeps the season airing whatever the status says",
		scenarios: ["canceled-with-episodes-left"],
		what: "The research's rule applies only when the show's status is not Ended or Canceled. TMDB sets Canceled when the network announces it, which can be weeks before the last episodes air. A caught-up member's show turns Seen with two episodes still listed ahead, and a week later it is \"Seen, new episodes\".",
		options: [
			"As the research has it.",
			"The status only shortens the wait: with Ended or Canceled a season is over as soon as nothing dated is ahead, without the 45 days. A dated episode ahead always keeps it airing.",
		],
		recommended: "The second.",
		inPrototype: "`endedStatus: \"closes-season\"` as the research reads. The second table runs `\"ignored-while-episodes-ahead\"`.",
	},
	{
		kind: "contradiction",
		title: "Aired by the member's date and aired by the UTC date disagree for some hours",
		short: "The member's date as settled, UTC when the member's zone is not known, and marking is never blocked",
		scenarios: ["airs-today-los-angeles", "airs-today-auckland"],
		what: "The map says an episode has aired when its air date is today or earlier for the member. The research proposes the UTC date, because TMDB's date has no time zone and one rule is simpler to compute. For an episode dated October 7, a member in Los Angeles at 18:00 on October 6 sees it as aired under UTC and not under their own date; a member in Auckland at 08:00 on October 7 sees the opposite. Neither is the broadcast: TMDB's date is the original network's day. Both rules are early for most members by up to a day. UTC is also late, by up to 14 hours, for members east of UTC watching a broadcast early in their own day (late-night shows in Japan, for example). The member's date is late only for a member far west of the broadcaster.",
		options: [
			"The member's date. Needs the member's time zone wherever the state is computed, and two members can see different states at the same moment.",
			"The UTC date. One answer for everybody and for SQL. Late for some members east of UTC.",
			"The member's date, and UTC wherever the zone is not at hand.",
		],
		recommended: "The third, with the rule that makes the difference harmless: a member can always mark a listed episode by hand, aired or not. \"Aired\" then only decides what Seen and the bulk marks include, what the next episode is, and what counts toward progress. It never stops a member from recording what they watched.",
		inPrototype: "`airedBy: \"member-date\"` as the map says. The second tables run `\"utc-date\"`. `markUnaired: \"allowed\"` is the proposal.",
	},
	{
		kind: "odd",
		title: "The next episode is the oldest gap, however far the member is",
		short: "The first unwatched episode after the furthest watched one, else the oldest gap",
		scenarios: ["starting-in-the-middle", "tmdb-readds-episode-watching"],
		what: "The glossary's next episode is the earliest aired regular episode without a watch. A member who starts marking at season 2 gets S1E1 as next episode until they fill season 1. A member who skipped one episode years ago gets that episode forever. A re-added episode (the ADR surprise above) does the same to everybody who watched it.",
		options: [
			"The earliest unwatched episode, as the glossary says. Always points at the oldest gap.",
			"The first unwatched episode after the furthest watched one, in season and episode order. When nothing is left after it, the oldest gap. Gaps stay visible in the progress numbers.",
			"The first unwatched episode after the most recently watched one. Not computable when watches have no date.",
		],
		recommended: "The second. The show still does not count as watched through while a gap exists, which is right: the member can fill it with \"mark up to here\" or leave it.",
		inPrototype: "`nextEpisode: \"earliest-unwatched\"` as the glossary says. The second table runs `\"after-furthest\"`.",
	},
	{
		kind: "contradiction",
		title: "A show can be Seen and have a status at the same time",
		short: "Allow both; where both hold, show the status",
		scenarios: ["rated-with-some-episodes", "new-season-on-seen-show"],
		what: "The glossary says a show status is where a person stands with a show they have not watched through, and that a rated show is Seen. A member who rates a show after three of ten episodes has a show that is Seen and Watching at 3 of 10, with a next episode. They can set it to Dropped and it is Seen and Dropped. A Seen show whose second season the member has started is Seen and Watching too. Nothing says which of the two a card or a filter shows.",
		options: [
			"Allow both. Seen keeps its meaning for Not seen yet and for taste; the status is what the member sees on the show wherever a status exists.",
			"A rating does not make a show Seen while it has unwatched aired episodes and a status. This changes the settled rule \"Seen when rated\".",
			"Rating a started show ends its status. Then rating is a way to lose your place in a show.",
		],
		recommended: "The first, and one changed sentence in the glossary: a show status is where a person stands with a show they have started and not finished.",
		inPrototype: "Both are stored and both are shown; no switch.",
	},
	{
		kind: "undefined",
		title: "A Seen show gets new episodes: no rule says what its status is or what a watch does",
		short: "No status until the member acts; any watch sets Watching; On hold and Dropped are offered",
		scenarios: ["new-season-on-seen-show", "weekly-network"],
		what: "\"The first watched episode sets Watching\" covers the first watch only. When a new season starts on a Seen show the member has watches and no status. Nothing says whether the show is Watching again by itself, whether marking S2E1 sets Watching, or whether the member can drop a show that is Seen.",
		options: [
			"No status while the member does nothing: the show is \"Seen, new episodes\". Marking an episode sets Watching. On hold and Dropped are offered because there is something left to watch.",
			"The show returns to Watching by itself when a new season starts. Then every show the member ever finished comes back into Watching unasked.",
		],
		recommended: "The first. Read \"the first watched episode sets Watching\" as: a watch by the member on a show without a status sets Watching.",
		inPrototype: "As recommended, a proposal with no switch (`watchedByMember` in `rules.ts`).",
	},
	{
		kind: "odd",
		title: "Existing Seen shows will say \"new episodes\" from the first day",
		short: "Accept it, and keep the sign quiet",
		scenarios: ["new-season-on-seen-show", "no-episode-list"],
		what: "The map gives a show already marked Seen bulk watches for the regular episodes that had aired by then. Every show a member marked Seen years ago and that has continued since comes out of the migration as \"Seen, new episodes\". For a member with a long history that is many shows at once.",
		options: [
			"Accept it: it is true, and it is what the feature is for.",
			"Mark every episode aired by the day of the migration. It claims watches nobody made.",
		],
		recommended: "The first. It is one more reason for \"new episodes\" to be a quiet sign on the show and not a list that demands attention; how it looks is still open on the map.",
		inPrototype: "`hasNewEpisodes` in `view()`: a Seen show with an unwatched regular episode that aired after the day it became Seen (or was first rated).",
	},
	{
		kind: "undefined",
		title: "Unmarking an episode of a Seen show",
		short: "It takes Seen away when the episode had aired by the day the show became Seen",
		scenarios: ["unmarking", "remove-seen-changes-nothing"],
		what: "The rules say what removing Seen does and nothing about unmarking one episode of a Seen show. If Seen stays, a mis-tap on the last episode cannot be undone: the show is Seen at 3 of 4 with a prompt to rate. If Seen goes, a member who marks a show Seen and then unmarks the one episode they skipped has a Watching show at 3 of 4 whose next episode is that one.",
		options: [
			"Unmarking an episode that had aired when the show became Seen takes Seen away; the show is Watching. Unmarking an episode of a later season leaves Seen alone.",
			"Seen stays whatever is unmarked, until the member removes Seen.",
			"Seen from a press stays, Seen from watching goes. Two kinds of Seen for the member to understand.",
		],
		recommended: "The first. Seen by watching stays explained by the watches, and an undo undoes. The member who skipped an episode has a show at 3 of 4, which is the truth; a rating makes it Seen.",
		inPrototype: "`unmarkOnSeen: \"removes-seen\"`, a proposal. The second table runs `\"keeps-seen\"`.",
	},
	{
		kind: "odd",
		title: "A mis-tap on the first episode costs the Want to See",
		short: "Unmarking the only watched episode ends Watching; Want to See is not restored",
		scenarios: ["unmarking"],
		what: "The first watched episode sets Watching and clears Want to See. Unmarking it takes the watch away. Nothing says what happens to the status, and the show has left the Wishlist for good. Left alone, the show would be Watching with nothing watched.",
		options: [
			"Unmarking the last watched episode ends Watching (On hold and Dropped stay, they are decisions). Want to See stays cleared.",
			"The same, and the undo offered right after the mark restores Want to See, because it still knows it was set.",
			"Store what the first watch cleared, and restore it whenever the show has no watch left.",
		],
		recommended: "The second: the rule is the first option, and the undo toast of the mark puts Want to See back. Nothing extra is stored.",
		inPrototype: "The first option (`afterRemoval` in `rules.ts`), a proposal.",
	},
	{
		kind: "undefined",
		title: "Before the first episode: Not interested, Dropped and On hold overlap",
		short: "Offer only Not interested; Dropped without an episode comes from imports; On hold needs an episode",
		scenarios: ["before-the-first-episode"],
		what: "Dropped is allowed with no episode watched, and once an episode is watched Dropped replaces Not interested. So with nothing watched both exist, and they do the same: hidden from recommendations, no taste signal, Want to See cleared. The only difference is that a Dropped show is also hidden by Not seen yet. Nothing says whether On hold is possible with nothing watched, or what setting Dropped does to Not interested.",
		options: [
			"With nothing watched the interface offers Not interested only. Dropped with nothing watched exists because a source says so, and is kept. On hold needs a watched episode. Setting Dropped clears Not interested, so a show has one of the two.",
			"Offer both from the start. The member has to learn a difference that barely exists.",
			"Turn an imported Dropped with no episode into Not interested. Simpler, and it loses what the source said.",
		],
		recommended: "The first.",
		inPrototype: "As recommended, proposals: `offered` in `view()`, and the refusals in `setOnHold` and `setNotInterested`.",
	},
	{
		kind: "undefined",
		title: "Want to See on a show the member has started",
		short: "On a started show with episodes left, wanting to see it means Watching",
		scenarios: ["on-hold-and-dropped", "before-the-first-episode"],
		what: "Adding Want to See clears Dropped. On a dropped show with three episodes watched that leaves watches and no status, and a show on the Wishlist that the first watch would have taken off it. Nothing says whether a Watching or On hold show can be on the Wishlist.",
		options: [
			"On a started show with episodes left, Want to See is not offered; what it would mean is Watching. If it arrives anyway (an imported watchlist), the show becomes Watching and does not go on the Wishlist.",
			"Want to See and a status can hold together. Then Watch next lists shows the member is in the middle of.",
			"It clears Dropped and nothing else, leaving a started show with no status.",
		],
		recommended: "The first. With no episode watched, Want to See clears Dropped and puts the show on the Wishlist as the glossary says. On a show watched through, Want to See stays possible: wanting to see it again.",
		inPrototype: "As recommended, a proposal (`addWantToSee`, and `offered.wantToSee` in `view()`).",
	},
	{
		kind: "undefined",
		title: "Whether watching a special starts a show",
		short: "No: a special changes nothing but its own mark",
		scenarios: ["specials", "specials-only"],
		what: "Specials can be watched and never count. Nothing says whether a special is \"the first watched episode\". If it is, a recap special sets Watching, clears Want to See and Not interested, and turns Dropped back to Watching. If it is not, a member can be Not interested in a show and have a watched special on it. A show that has only specials has nothing that can count: it cannot be started or watched through.",
		options: [
			"A special changes nothing but its own mark: no status, Want to See stays, the show is not hidden. A show with only specials can be marked Seen as a whole.",
			"A special starts the show like any episode. Then \"never counts\" has an exception, and a show can be Watching at 0 of 4.",
		],
		recommended: "The first.",
		inPrototype: "`specialStartsShow: false`, a proposal. Seen marks no special, and \"mark season\" on the specials marks the dated ones.",
	},
	{
		kind: "undefined",
		title: "A show marked Seen with no episode list gets a list later",
		short: "Give it bulk watches for what had aired when it was marked, as for existing rows",
		scenarios: ["no-episode-list"],
		what: "19,369 shows list no season. Such a show can only be marked Seen as a whole, with no watches behind it. When TMDB adds the episodes, the show is Seen at 0 of 9 and its next episode is S1E1, although the member said they have seen it.",
		options: [
			"When the list first appears, the show gets bulk watches, date unknown, for the regular episodes that had aired by the day it was marked Seen. That is the map's rule for existing rows, applied later. Episodes aired since then show as new.",
			"Nothing. Seen stays, with no progress behind it, like a rated show.",
		],
		recommended: "The first. It can run when the catalog copy first writes episodes for a show, or be worked out when reading: a Seen press with no watch behind it covers what had aired by its day.",
		inPrototype: "`backfillWhenListAppears: true`, a proposal. The second table runs `false`. Seen is not offered when a list exists and nothing has aired yet.",
	},
	{
		kind: "odd",
		title: "A rated show with no episode watched has a next episode and cannot be marked through Seen",
		short: "Next episode only where there is a status; a separate \"mark all aired\" in the episode list",
		scenarios: ["rated-without-episodes"],
		what: "A rating marks no episodes. The show is Seen at 0 of 6 and its next episode is S1E1. The Seen button already shows Seen, so pressing it would mean removing Seen, and the member has no single press to mark the episodes they watched. Neither Not interested nor Dropped is offered. When season 2 starts the show says \"new episodes\", counted from the day of the rating, so rating it again later would hide them.",
		options: [
			"Surfaces show a next episode only for a show with a status. The episode list has its own \"mark all aired\", which is the Seen press under another name. \"New episodes\" counts from the first rating, not the latest.",
			"A rating marks every aired episode. This changes the settled rule \"a rating marks no episodes\".",
		],
		recommended: "The first.",
		inPrototype: "`view().nextEpisode` is given for every show; the prototype's Seen press marks episodes on a rated show too. `hasNewEpisodes` counts from the stored rating time, which is the latest.",
	},
	{
		kind: "undefined",
		title: "On hold and Dropped when everything is watched, and a rating on a Dropped show",
		short: "Time never changes On hold or Dropped; a rating stays a taste signal",
		scenarios: ["on-hold-and-dropped", "rated-with-some-episodes", "import-old-history"],
		what: "A member can be caught up and set Dropped. When the season then ends, the show is watched through with no season airing, which is the definition of Seen. Nothing says whether it turns Seen and loses Dropped by itself. Dropped is not a taste signal, and nothing says whether a rating on a Dropped show still is one.",
		options: [
			"The calendar never changes On hold or Dropped. Only the member does: by watching an episode, pressing Seen, or setting another status. A rating on a Dropped show counts for taste like any rating; the show stays hidden from recommendations.",
			"A show that is watched through with no season airing is Seen whatever its status. A dropped show would come back unasked.",
		],
		recommended: "The first.",
		inPrototype: "As recommended: `settle` in `rules.ts` turns only a Watching show, or one without a status, Seen. Taste is not modelled.",
	},
	{
		kind: "undefined",
		title: "Marking an episode that has not aired, and what progress counts",
		short: "Allowed by hand; progress counts aired episodes only and never the listed total",
		scenarios: ["airs-today-los-angeles", "no-air-date", "weekly-network", "streaming-season"],
		what: "The rules say what bulk marks include (aired regular episodes) and nothing about one mark by hand on an episode that has not aired or has no date. They do not say what progress is measured against either. The listed count is wrong as a total: a weekly network season lists 6 episodes when it will have 22.",
		options: [
			"A mark by hand is always allowed. Progress is watched aired episodes over aired episodes; a watched episode that has not aired joins the count when it airs. The listed count is shown as a season's length only when its finale is marked.",
			"Episodes that have not aired cannot be marked. Then a wrong or missing date at TMDB, or a time zone, blocks the member.",
		],
		recommended: "The first.",
		inPrototype: "`markUnaired: \"allowed\"`, a proposal. The report prints progress as watched/aired and adds the listed count when it is larger.",
	},
	{
		kind: "undefined",
		title: "When the one prompt to rate appears",
		short: "Once per show, the first time it becomes Seen by a watch or a press; never from an import or the calendar alone",
		scenarios: ["start-and-finish", "weekly-network", "seen-press-while-airing", "import-old-history"],
		what: "One dismissible prompt to rate when a show is watched through. Running it raises four questions. Does catching up mid-season count as watched through? Does a Seen press ask? Does it ask again when the member finishes a later season? Does it ask when the show turned Seen because 45 days ran out, or because an import brought a finished show?",
		options: [
			"Once per show, when it first becomes Seen by the member's own watch or press, and only if it is not rated. Not for caught up, not again for later seasons, not from an import, and not at the moment the calendar turns the show Seen (it can appear on the member's next visit to the show).",
			"Every time a show becomes watched through, including later seasons.",
		],
		recommended: "The first.",
		inPrototype: "Simpler than the recommendation: the prompt shows while the show has a Seen mark, no rating, and the prompt was not dismissed. The tables therefore show it after an import and after the 45 days.",
	},
	{
		kind: "undefined",
		title: "What imported watches do to a status",
		short: "They start a show without a status and never override On hold or Dropped",
		scenarios: ["import-old-history"],
		what: "Watching an episode of an On hold or Dropped show returns it to Watching. An import adds watches that happened long ago. If they count as watching, importing a history turns every show the member dropped by hand back to Watching.",
		options: [
			"An imported watch sets Watching only on a show without a status. On hold and Dropped stay unless the import itself brings a status for the show.",
			"Compare dates: an imported watch dated after the status changed returns the show to Watching. Not possible for watches without a date.",
		],
		recommended: "The first.",
		inPrototype: "As recommended, a proposal (`importWatches` in `rules.ts`).",
	},
	{
		kind: "undefined",
		title: "Marking over existing watches, and what unmarking removes",
		short: "Bulk marks skip watched episodes; unmarking removes every watch of the episode",
		scenarios: ["remove-seen-with-hand-marks", "tmdb-readds-episode-watching"],
		what: "A watch is its own row and an episode can have several. Nothing says whether Seen or \"mark season\" adds a second watch to an episode that has one, or which watch an unmark removes when there are a dated one from an import and a bulk one.",
		options: [
			"Bulk marks and single marks add a watch only where the episode has none. Unmarking removes every watch of the episode, whatever its origin, because the member is saying \"I have not watched this\". A second watch of an episode comes only from an import or a later \"Watch again\".",
			"Unmarking removes the newest watch only. An episode from an import with two watches needs two presses to unmark.",
		],
		recommended: "The first. The episode list should say so when an unmark removes a dated watch.",
		inPrototype: "As recommended, a proposal (`bulkMark` and `unmarkEpisode` in `rules.ts`).",
	},
]
