services:
  embeddings:
    build:
      context: ./embeddings
      dockerfile: Dockerfile
    ports:
      - "7997:80"
    restart: unless-stopped
    environment:
      - HUGGING_FACE_HUB_TOKEN
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"

#  embeddings:
#    image: michaelf34/infinity:latest
#    restart: unless-stopped
#    ports:
#      - "7997:7997"
#    volumes:
#      - embeddings_cache:/app/.cache
#    command: >
#      v2
#      --model-id BAAI/bge-m3
#      --port 7997

#volumes:
#  embeddings_cache:
