version: '3'

services:
  redis-main:
    image: docker.io/bitnami/redis-cluster:7.2
    volumes:
      - redis-data:/bitnami/redis/data
    ports:
      - "6379:6379"
      - "16379:16379"
      - "16380:16380"
      - "16381:16381"
    environment:
      - 'REDIS_NODES=78.46.209.172 168.119.242.21'
      - 'REDIS_PASSWORD=${REDIS_PASSWORD}'
      - 'REDISCLI_AUTH=${REDIS_PASSWORD}'
      - 'REDIS_CLUSTER_REPLICAS=1'
      - 'REDIS_CLUSTER_CREATOR=yes'

volumes:
  redis-data:
    driver: local