x-logging: &default-logging
  driver: "json-file"
  options:
    max-size: "100m"
    max-file: "10"

services:
  redis-replica:
    image: docker.io/bitnami/redis-cluster:7.2
    restart: unless-stopped
    volumes:
      - redis-data:/bitnami/redis/data
    network_mode: host
    environment:
      - 'REDIS_NODES=10.0.0.14 10.0.0.15 10.0.0.16'
      - 'REDIS_CLUSTER_DYNAMIC_IPS=no'
      - 'REDIS_CLUSTER_ANNOUNCE_IP=${REDIS_PRIVATE_IP:?Set the node private address (10.0.0.14-16)}'
      - 'REDIS_PASSWORD=${REDIS_PASSWORD}'
    logging: *default-logging
    command:
      - /opt/bitnami/scripts/redis-cluster/run.sh
      - --cluster-announce-ip
      - "${REDIS_PRIVATE_IP:?Set the node private address (10.0.0.14-16)}"
      - --cluster-announce-port
      - "6379"
      - --cluster-announce-bus-port
      - "16379"

volumes:
  redis-data:
    driver: local
