version: '3'

services:
  redis-replica:
    image: docker.io/bitnami/redis-cluster:7.2
    volumes:
      - redis-data:/bitnami/redis/data
    ports:
      - "6379:6379"
    environment:
      - 'REDIS_NODES=78.46.209.172 168.119.242.21'
      - 'REDIS_PASSWORD=${REDIS_PASSWORD}'

volumes:
  redis-data:
    driver: local