version: '3'

services:
  redis-replica:
    image: docker.io/bitnami/redis-cluster:7.2
    volumes:
      - redis-data:/bitnami/redis/data
    network_mode: host
    ports:
      - "6379:6379"
      - "16379:16379"
      - "16380:16380"
      - "16381:16381"
    environment:
      - 'REDIS_NODES=78.46.209.172 168.119.242.21 91.107.208.205'
      - 'REDIS_PASSWORD=${REDIS_PASSWORD}'
    command:
      - /opt/bitnami/scripts/redis-cluster/run.sh
      - --cluster-announce-ip
      - "${REDIS_HOST_IP}"

volumes:
  redis-data:
    driver: local