// PROTOTYPE - throwaway. Words for naming a taste: an adjective, a plural noun for the kind of title,
// and a persona for each non-craft fingerprint attribute. Used to name sides and the archetype.

export const WORDS: Record<
	string,
	[adj: string, noun: string, persona: string]
> = {
	adrenaline: ["high-octane", "adrenaline rushes", "adrenaline chaser"],
	tension: ["white-knuckle", "nail-biters", "tension addict"],
	scare: ["nightmare-fed", "horror", "horror hound"],
	violence: ["hard-edged", "brutal stories", "bruiser"],
	romance: ["romantic", "love stories", "romantic"],
	eroticism: ["sensual", "sensual dramas", "sensualist"],
	wholesome: ["warm-hearted", "feel-good stories", "softie"],
	wonder: ["wide-eyed", "adventures full of wonder", "wonder seeker"],
	pathos: ["tender", "heartbreakers", "heartbreak collector"],
	melancholy: ["melancholic", "bittersweet stories", "melancholic"],
	uncanny: ["eerie", "uncanny tales", "seeker of the uncanny"],
	catharsis: ["cathartic", "cathartic dramas", "catharsis seeker"],
	nostalgia: ["nostalgic", "nostalgia trips", "nostalgist"],
	situational_comedy: ["sitcom-style", "sitcoms", "sitcom loyalist"],
	wit_wordplay: ["quick-witted", "sharp-tongued comedies", "wordsmith"],
	physical_comedy: ["slapstick", "slapstick comedies", "slapstick fan"],
	cringe_humor: ["cringe-proof", "cringe comedies", "cringe connoisseur"],
	absurdist_humor: ["absurdist", "absurd comedies", "absurdist"],
	satire_parody: ["satirical", "satires", "satirist"],
	dark_humor: ["pitch-black", "pitch-black comedies", "gallows humorist"],
	fantasy: ["myth-minded", "fantasy epics", "fantasist"],
	futuristic: ["future-bound", "visions of the future", "futurist"],
	historical: ["period", "period pieces", "history buff"],
	contemporary_realism: ["grounded", "grounded dramas", "realist"],
	crime: ["crime-soaked", "crime stories", "crime devotee"],
	mystery: ["puzzle-minded", "mysteries", "sleuth"],
	warfare: ["battle-scarred", "war stories", "war chronicler"],
	political: ["political", "political thrillers", "political animal"],
	sports: ["competitive", "sports stories", "sports fan"],
	biographical: ["true-story", "true stories", "biography reader"],
	coming_of_age: ["coming-of-age", "coming-of-age stories", "late bloomer"],
	family_dynamics: ["family-minded", "family sagas", "family chronicler"],
	psychological: ["mind-game", "psychological thrillers", "mind reader"],
	showbiz: ["backstage", "showbiz stories", "showbiz insider"],
	gaming: ["gamer", "game worlds", "gamer"],
	pop_culture: ["pop-savvy", "pop-culture riffs", "pop-culture magpie"],
	social_commentary: ["socially sharp", "social critiques", "social critic"],
	class_and_capitalism: [
		"class-conscious",
		"stories about money and class",
		"class warrior",
	],
	technology_and_humanity: [
		"tech-haunted",
		"stories about tech and us",
		"tech skeptic",
	],
	spiritual: ["spiritual", "spiritual journeys", "seeker"],
	slow_burn: ["slow-burning", "slow burns", "slow-burner"],
	fast_pace: ["breakneck", "breakneck thrillers", "speed freak"],
	intrigue: ["scheming", "stories of intrigue", "intrigue hunter"],
	complexity: ["intricate", "complex puzzles", "complexity junkie"],
	hopefulness: ["hopeful", "hopeful stories", "optimist"],
	bleakness: ["bleak", "bleak dramas", "pessimist"],
	ambiguity: ["morally grey", "morally grey stories", "grey-zone dweller"],
	novelty: ["restless", "true originals", "novelty hunter"],
	homage_and_reference: ["referential", "homages", "cinephile"],
	non_linear_narrative: [
		"time-twisting",
		"puzzle-box timelines",
		"puzzle-box fan",
	],
	meta_narrative: ["self-aware", "meta stories", "meta-fiction fan"],
	surrealism: ["dreamlike", "surreal trips", "surrealist"],
	eccentricity: ["eccentric", "stories full of eccentrics", "eccentric"],
	philosophical: ["big-question", "big-idea stories", "philosopher"],
	educational: ["curious", "things that teach you something", "student"],
	world_immersion: ["world-building", "immersive worlds", "world traveler"],
	spectacle: ["big-screen", "spectacles", "spectacle chaser"],
	visual_stylization: ["stylish", "stylized films", "aesthete"],
	pastiche: ["genre-remixing", "pastiches", "genre remixer"],
	psychedelic: ["psychedelic", "psychedelic trips", "tripper"],
	grotesque: ["grotesque-loving", "grotesque tales", "gorehound"],
	camp_and_irony: ["camp", "camp classics", "camp lover"],
	dialogue_centrality: ["talky", "talky dramas", "listener"],
	music_centrality: ["musical", "musicals", "music lover"],
	sound_centrality: ["sound-obsessed", "sound-driven films", "listener"],
}

export const adj = (k: string) => WORDS[k]?.[0] ?? k.replace(/_/g, " ")
export const noun = (k: string) => WORDS[k]?.[1] ?? k.replace(/_/g, " ")
export const persona = (k: string) => WORDS[k]?.[2] ?? k.replace(/_/g, " ")
export const cap = (s: string) => s.charAt(0).toUpperCase() + s.slice(1)

export const CONTEXTS: { id: string; name: string; line: string }[] = [
	{
		id: "thought_provoking",
		name: "Something to think about",
		line: "Titles that stay with you after the credits",
	},
	{
		id: "comfort_watch",
		name: "Comfort watch",
		line: "Familiar, warm, easy to return to",
	},
	{
		id: "pure_escapism",
		name: "Pure escapism",
		line: "Other worlds, no homework",
	},
	{
		id: "binge_friendly",
		name: "A long binge",
		line: "Hard to stop after one",
	},
	{
		id: "drop_in_friendly",
		name: "Drop in anytime",
		line: "Pick it up anywhere",
	},
	{
		id: "background_friendly",
		name: "On in the background",
		line: "Fine while you do something else",
	},
]

/** Two demo friends to compare against. Real friends would need consent and a follow model. */
export const FRIENDS: {
	id: string
	name: string
	blurb: string
	ratings: Record<string, number>
}[] = [
	{
		id: "mia",
		name: "Mia",
		blurb: "Demo friend: animation, fantasy, and comfort sitcoms",
		ratings: {
			"movie-120": 9,
			"movie-121": 9,
			"movie-862": 9,
			"movie-585": 8,
			"movie-671": 8,
			"movie-11": 8,
			"movie-105": 9,
			"movie-329": 8,
			"movie-194": 9,
			"movie-129": 10,
			"movie-4935": 9,
			"movie-120467": 8,
			"movie-546554": 8,
			"movie-8363": 7,
			"movie-22538": 8,
			"movie-14160": 9,
			"movie-10681": 9,
			"movie-150540": 9,
			"movie-354912": 9,
			"movie-13": 8,
			"movie-299534": 7,
			"movie-95": 4,
			"movie-106646": 4,
			"movie-769": 5,
			"movie-64690": 5,
			"movie-603": 8,
			"movie-27205": 8,
			"movie-155": 7,
			"show-1399": 7,
			"show-66732": 8,
			"show-1668": 9,
			"show-2316": 8,
			"show-97546": 10,
			"show-48891": 9,
			"show-1421": 8,
			"show-94605": 9,
			"show-70785": 9,
			"show-73586": 3,
			"show-60625": 6,
			"show-1396": 7,
		},
	},
	{
		id: "jonas",
		name: "Jonas",
		blurb: "Demo friend: slow arthouse, melancholy, and romance",
		ratings: {
			"movie-843": 10,
			"movie-18148": 9,
			"movie-11216": 9,
			"movie-426": 9,
			"movie-467244": 9,
			"movie-398818": 8,
			"movie-76": 9,
			"movie-38": 9,
			"movie-152601": 8,
			"movie-194662": 8,
			"movie-64690": 8,
			"movie-313369": 7,
			"movie-1417": 9,
			"movie-11621": 8,
			"movie-4922": 6,
			"movie-19995": 4,
			"movie-299534": 3,
			"movie-95": 2,
			"movie-284054": 4,
			"movie-8363": 3,
			"movie-155": 6,
			"movie-603": 7,
			"movie-27205": 6,
			"movie-550": 7,
			"movie-680": 8,
			"show-136315": 9,
			"show-42009": 8,
			"show-100088": 8,
			"show-1400": 7,
			"show-93405": 6,
			"show-82856": 4,
			"show-71912": 4,
			"show-1668": 5,
			"show-1396": 8,
		},
	},
]
