services:
  highperf_worker:
    build:
      context: ../worker
      args:
        WM_IMAGE: ${WM_IMAGE}
    pull_policy: always
    deploy:
      replicas: ${WORKER_COUNT}
      resources:
        limits:
          cpus: "6"
          memory: 20048M
    restart: unless-stopped
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - RUST_LOG=info
      - DISABLE_SERVER=true
      - KEEP_JOB_DIR=false
      - METRICS_ADDR=false
      - WORKER_GROUP=${WORKER_GROUP}-highperf
      - WORKER_TAGS=highperf
      # LICENSE_KEY is only needed for the enterprise edition
      - LICENSE_KEY=${WM_LICENSE_KEY}
    depends_on:
      db:
        condition: service_healthy
    # to mount the worker folder to debug, KEEP_JOB_DIR=true and mount /tmp/windmill
    volumes:
      # mount the docker socket to allow to run docker containers from within the workers
      - /var/run/docker.sock:/var/run/docker.sock
      - worker_dependency_cache:/tmp/windmill/cache

volumes:
  worker_dependency_cache: null
