// PROTOTYPE - throwaway. Generated by a scratch script (explorer2/gencss.mjs) from the class names in this folder:
// the dev server's stylesheet can lag behind new files, so round 2 ships its own copy of the utilities it uses.
export const GENERATED_CSS_2 = "@layer utilities;\n"
