---
- name: Set up cron job to periodically kill zombie processes
  hosts: all
  become: yes

  tasks:
    - name: Ensure the cron job is present
      cron:
        name: "Kill windmill process every 24 hours"
        minute: "0"
        hour: "23"
        job: "/usr/bin/killall -9 windmill"
