services:
  grafana-alloy:
    image: grafana/alloy:latest
    container_name: grafana-alloy
    env_file:
      - .env
    volumes:
      # Mount the configuration file read-only
      - ./config.alloy:/etc/alloy/config.alloy:ro
      # Mount necessary host directories for the node_exporter component (read-only)
      - /proc:/proc:ro
      - /sys:/sys:ro
      # Mount root filesystem read-only if filesystem metrics are needed (usually covered by /proc, /sys)
      # - /:/host/root:ro # Might be needed for specific collectors, start without it.
    # Ports (Optional): Expose Alloy's own UI/metrics endpoint if enabled in config.alloy
    # ports:
    #   - "127.0.0.1:12345:12345" # Expose only on localhost for security
    restart: unless-stopped
    #security_opt:
    #  - apparmor:unconfined
    # Run Alloy with the specified configuration file
    command: run /etc/alloy/config.alloy
    # Security Context: Important for accessing host metrics
    # The node_exporter component needs access to host resources.
    # Start with minimal privileges. If metrics are missing (e.g., detailed network stats),
    # you might need to add capabilities or, as a last resort, run as privileged/host PID.
    # pid: host # If process-related metrics are missing
    # cap_add:
    #   - SYS_TIME # Allows changing system time (less likely needed for exporter)
    #   - NET_ADMIN # Often needed for detailed network interface statistics
    #   - SYS_PTRACE # Needed for some process metrics
    privileged: true # Avoid if possible, grants full host access