services:
  grafana-alloy:
    image: grafana/alloy:v1.7.5
    container_name: grafana-alloy
    env_file:
      - .env
    volumes:
      - ./config.alloy:/etc/alloy/config.alloy:ro
    restart: unless-stopped
    security_opt:
      - apparmor:unconfined
    command: run /etc/alloy/config.alloy
    depends_on:
      - node-exporter

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: unless-stopped
    # Node Exporter needs access to host resources
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/host/root:ro # Mount host root for filesystem metrics
    # Needs host PID namespace to read all processes correctly
    pid: host
    # Command line arguments for node_exporter
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--path.rootfs=/host/root'
      # Optional: Disable collectors you don't need, e.g.:
      # - '--collector.textfile.directory=/var/lib/node_exporter/' # Example default
      # - '--no-collector.arp'
      # - '--no-collector.netstat'
    # No ports needed externally, Alloy scrapes it via Docker network
    # Ports are mapped internally by Docker Compose networking

# Define the default bridge network if not already explicit
# networks:
#   default:
#     driver: bridge