services:
  # Grafana Alloy - now without host /proc and /sys mounts
  grafana-alloy:
    image: grafana/alloy:v1.7.5 # Keep pinned version for now
    container_name: grafana-alloy
    env_file:
      - .env
    volumes:
      # Only mount the configuration file
      - ./config.alloy:/etc/alloy/config.alloy:ro
      # NO /proc or /sys mounts here anymore
    restart: unless-stopped
    # Keep this for now, although it might not be strictly needed anymore
    # if removing the volumes fixes the init issue. Start with it included.
    security_opt:
      - apparmor:unconfined
    # OR privileged: true # You only need one, use security_opt first.
    command: run /etc/alloy/config.alloy
    # Alloy depends on node-exporter being available
    depends_on:
      - node-exporter

  # Separate Node Exporter container
  node-exporter:
    image: prom/node-exporter:latest # Use official node_exporter image
    container_name: node-exporter
    restart: unless-stopped
    # Node Exporter needs access to host resources
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/host/root:ro # Mount host root for filesystem metrics
    # Needs host PID namespace to read all processes correctly
    pid: host
    # Command line arguments for node_exporter
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--path.rootfs=/host/root'
      # Optional: Disable collectors you don't need, e.g.:
      # - '--collector.textfile.directory=/var/lib/node_exporter/' # Example default
      # - '--no-collector.arp'
      # - '--no-collector.netstat'
    # No ports needed externally, Alloy scrapes it via Docker network
    # Ports are mapped internally by Docker Compose networking

# Define the default bridge network if not already explicit
# networks:
#   default:
#     driver: bridge