x-logging: &default-logging
  driver: "json-file"
  options:
    max-size: "100m"
    max-file: "10"

services:
  uptime-kuma:
    image: louislam/uptime-kuma:1
    volumes:
      - uptime-kuma-data:/app/data
    ports:
      - 4801:3001
    restart: always
    logging: *default-logging

volumes:
  uptime-kuma-data:
