#!/usr/bin/env python3
"""THROWAWAY self-contained human review artifact; no network or persistence."""
import json,pathlib
here=pathlib.Path(__file__).resolve().parent
text='''<!doctype html><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>Translation before search — prototype review</title>
<style>body{font:16px system-ui;max-width:1400px;margin:40px auto;padding:0 20px;color:#172b35;background:#f8fafb}h1{font-size:28px}button,select{font:inherit;padding:9px;margin:4px;border:1px solid #ccd5df;border-radius:5px;background:white}button[aria-selected=true]{background:#d6f4ed}section{margin:24px 0;padding:20px;background:white;border:1px solid #dce3e6;border-radius:8px}.columns{display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:16px}li{margin:8px 0}small{color:#596671}.state{background:#e4f3ef;padding:16px}pre{white-space:pre-wrap}td,th{text-align:left;padding:8px;border-bottom:1px solid #ddd}table{width:100%;font-size:14px}</style>
<h1>Does translation preserve the search request?</h1><p>Throwaway logic prototype: compare measured translations and top-ten results with the accepted English and native baselines. New results need your relevance judgment; matching titles alone do not establish quality. All data below is captured, not a live search.</p>
<h2>Explore the path</h2><p>These walkthroughs use recorded data. Failure is deliberately injected; the vector-only output was actually retrieved.</p><div id="tabs"></div><div class="state" id="state"></div><div id="actions"></div>
<h2>Measured comparisons</h2><p>Select a model; then review whether its translated request and results preserve the intent, especially exclusions. The alternative and failure path remain visible.</p><select id="model"></select><div id="comparisons"></div><h2>Local language check</h2><p>Five-language detector experiment. Title lookups bypass it. Short ambiguous words and unsupported or mixed languages are not proven safe by this small set.</p><div id="detection"></div>
<script>
const data=DATA;
const model=document.querySelector('#model'); for(const m of Object.keys(data.models))model.add(new Option(m,m));
const scenarios=[['English request',['english','search']],['German request',['german','translate','search']],['Translation unavailable',['german','fail']],['Repeated translation',['german','translate','repeat','search']]];
function initial(){return {language:'unknown',request:'No request selected',translation:null,path:'waiting',cache:{},cost:0,latency:0,notice:'Choose a walkthrough or press any action.'}}
function transition(s,a){s=structuredClone(s);const sample=data.cases[0].models[model.value].translation;
if(a==='english'||a==='german'){s={...s,language:a==='english'?'English':'German',request:a==='english'?data.cases[0].english_fixture.query:data.cases[0].fixture.query,translation:null,path:a==='english'?'skip translation':'translation required',cost:0,latency:0,notice:'Original request retained.'}}
if(a==='translate'&&s.language==='German'){s.translation=sample.text;s.cache[s.request]=sample.text;s.cost=sample.usage.cost;s.latency=sample.ms;s.path='ready for unchanged D4+';s.notice='One measured translation call.'}
if(a==='repeat'&&s.cache[s.request]){s.translation=s.cache[s.request];s.cost=0;s.latency=0;s.path='ready from translation cache';s.notice='Simulated warm-cache hit; cache must include model and prompt versions.'}
if(a==='search'){s.path=s.language==='English'||s.translation?'unchanged D4+':'waiting for translation';s.notice='Translation completes before both Jev calls.'}
if(a==='fail'){s.translation=null;s.path='native Jev + vector only';s.notice='No text evidence query. Failure is not stored as a successful translation.'}
return s}
let state=initial(); const actions={english:'Enter English',german:'Enter German',translate:'Translate successfully',search:'Run search',fail:'Translation fails',repeat:'Repeat cached request'};
function act(a){state=transition(state,a);renderState()}function renderState(){const box=document.querySelector('#state');box.replaceChildren();for(const [k,v] of Object.entries(state)){const p=document.createElement('p');p.textContent=k+': '+(typeof v==='object'?JSON.stringify(v):v);box.append(p)}}
for(const [a,label]of Object.entries(actions)){const b=document.createElement('button');b.textContent=label;b.onclick=()=>act(a);document.querySelector('#actions').append(b)}
for(const [name,steps]of scenarios){const b=document.createElement('button');b.textContent=name;b.onclick=()=>{state=initial();renderState();document.querySelector('#steps')?.remove();const d=document.createElement('div');d.id='steps';steps.forEach(a=>{const x=document.createElement('button');x.textContent=actions[a];x.onclick=()=>act(a);d.append(x)});document.querySelector('#tabs').append(d)};document.querySelector('#tabs').append(b)}
function node(tag,text,parent){const n=document.createElement(tag);n.textContent=text;parent.append(n);return n}
function list(parent,title,response,accepted){const div=node('div','',parent);node('h3',title,div);const ol=node('ol','',div);for(const r of response.results.slice(0,10)){const id=r.media_type+':'+r.tmdb_id;node('li',r.title+' ('+r.release_year+')'+(accepted&&!accepted.has(id)?' — NEW, review':'')+' · '+id,ol)}}
function render(){const root=document.querySelector('#comparisons');root.replaceChildren();for(const c of data.cases){const section=node('section','',root),v=c.models[model.value],accepted=new Set(c.accepted_english.results.slice(0,10).map(r=>r.media_type+':'+r.tmdb_id));node('h2',c.fixture.id+' · '+c.fixture.intent,section);node('p','Original: '+c.fixture.query,section);node('p','Translation: '+v.translation.text,section);node('p','English reference: '+c.english_fixture.query,section);node('small','Translation '+Math.round(v.translation.ms)+' ms · $'+v.translation.usage.cost+' · '+v.accepted_english_overlap+'/10 titles overlap the accepted English list. Quality pending human review.',section);const columns=node('div','',section);columns.className='columns';list(columns,'Accepted English',c.accepted_english);list(columns,'Translated request',v.search.response,accepted);list(columns,'Accepted native',c.accepted_native);list(columns,'Translation failure: vectors',c.fallback.response,accepted);const details=node('details','',section);node('summary','Fresh English control and full measurement',details);list(details,'Fresh English control',c.fresh_english.response,accepted);node('pre',JSON.stringify({translation:v.translation,translatedSearchMs:v.search.http_ms,fallbackMs:c.fallback.http_ms},null,2),details)}}
model.onchange=render;render();renderState();const table=node('table','',document.querySelector('#detection'));for(const d of data.detection){const tr=node('tr','',table);for(const value of [d.id,d.query,d.language,d.translate?'translate':'skip',d.ms.toFixed(2)+' ms'])node('td',value,tr)}
</script>'''
(here/'review.html').write_text(text.replace('DATA',json.dumps(json.loads((here/'results.json').read_text()),ensure_ascii=False).replace('<','\\u003c')))
