"""CPU query-embedding latency (4 threads) and a top-10 sanity check per model.

Usage: .venv/bin/python scripts/latency_and_sanity.py
Writes data/latency.json and data/sanity.md.
"""
import json, os, sys, time
import numpy as np

sys.path.insert(0, os.path.dirname(__file__))
from embed_catalog import DATA, MODELS, load_catalog

THREADS = 4
LATENCY_QUERIES = [
    "fantasy with dragons", "scifi with cars", "feel good cooking show", "grief after losing a child",
    "melancholy lighthouse keeper mystery", "heist movie set in a casino with a twist ending",
    "cozy anime about a witch delivering bread", "something like Twin Peaks but funnier",
    "películas de terror en español", "a slow documentary about bees",
]
SANITY_QUERIES = LATENCY_QUERIES[:5]
ONNX_REPO = {
    "bge-small-en-v1.5": "Xenova/bge-small-en-v1.5",
    "e5-small-v2": "Xenova/e5-small-v2",
    "bge-base-en-v1.5": "Xenova/bge-base-en-v1.5",
    "multilingual-e5-small": "Xenova/multilingual-e5-small",
}


def pctl(xs, p):
    return round(float(np.percentile(xs, p)), 1)


def time_fn(fn, queries, reps=5):
    for q in queries[:3]:
        fn(q)  # warmup
    ts = []
    for _ in range(reps):
        for q in queries:
            t = time.perf_counter()
            fn(q)
            ts.append((time.perf_counter() - t) * 1000)
    return {"p50_ms": pctl(ts, 50), "p90_ms": pctl(ts, 90)}


def torch_cpu(name):
    import torch
    from sentence_transformers import SentenceTransformer
    torch.set_num_threads(THREADS)
    m = SentenceTransformer(MODELS[name]["hf"], device="cpu")
    pre = MODELS[name]["query"]
    return lambda q: m.encode([pre + q], normalize_embeddings=True)[0]


def onnx_cpu(name, variant):
    import onnxruntime as ort
    from huggingface_hub import hf_hub_download
    from tokenizers import Tokenizer
    repo = ONNX_REPO[name]
    path = hf_hub_download(repo, f"onnx/{variant}.onnx")
    tok = Tokenizer.from_file(hf_hub_download(repo, "tokenizer.json"))
    so = ort.SessionOptions()
    so.intra_op_num_threads = THREADS
    so.inter_op_num_threads = 1
    sess = ort.InferenceSession(path, so, providers=["CPUExecutionProvider"])
    inputs = {i.name for i in sess.get_inputs()}
    pre = MODELS[name]["query"]
    is_bge = name.startswith("bge")

    def enc(q):
        e = tok.encode(pre + q)
        ids = np.array([e.ids], dtype=np.int64)
        mask = np.array([e.attention_mask], dtype=np.int64)
        feed = {"input_ids": ids, "attention_mask": mask}
        if "token_type_ids" in inputs:
            feed["token_type_ids"] = np.zeros_like(ids)
        h = sess.run(None, feed)[0][0]
        v = h[0] if is_bge else (h * mask[0][:, None]).sum(0) / mask.sum()  # bge: CLS, e5: mean pooling
        return v / np.linalg.norm(v)

    return enc


def main():
    rows = load_catalog()
    ids = json.load(open(os.path.join(DATA, "emb-ids.json")))
    assert ids == [r["id"] for r in rows]
    popular = np.array([r["votes"] >= 2000 for r in rows])
    latency, sanity = {}, ["# Sanity: top 10 by cosine (votes >= 2000)", "",
                           "Query prefix per model as in scripts/embed_catalog.py. Generated by scripts/latency_and_sanity.py.", ""]
    tops = {}
    for name in MODELS:
        emb = np.load(os.path.join(DATA, f"emb-{name}.npy")).astype(np.float32)
        ref = torch_cpu(name)
        latency[name] = {"torch_fp32": time_fn(ref, LATENCY_QUERIES)}
        for variant in ["model", "model_quantized"]:
            enc = onnx_cpu(name, variant)
            agree = float(np.mean([enc(q) @ ref(q) for q in LATENCY_QUERIES]))
            latency[name][f"onnx_{variant}"] = {**time_fn(enc, LATENCY_QUERIES), "cos_vs_torch": round(agree, 4)}
        print(name, json.dumps(latency[name]), flush=True)
        for q in SANITY_QUERIES:
            s = emb @ ref(q)
            s[~popular] = -9
            top = np.argsort(-s)[:10]
            tops.setdefault(q, {})[name] = [f"{rows[i]['title']} ({rows[i]['year']}, {rows[i]['media_type']}) {s[i]:.3f}" for i in top]
    for q, per in tops.items():
        sanity += [f"## {q}", ""]
        for name, lst in per.items():
            sanity += [f"**{name}**", ""] + [f"{k + 1}. {t}" for k, t in enumerate(lst)] + [""]
    open(os.path.join(DATA, "sanity.md"), "w").write("\n".join(sanity))
    json.dump({"threads": THREADS, "cpu": os.popen("lscpu | grep 'Model name'").read().strip(), "results": latency},
              open(os.path.join(DATA, "latency.json"), "w"), indent=1)


if __name__ == "__main__":
    main()
