"""Render private iterative search results as a standalone, local review page."""
import argparse
import json
from pathlib import Path

HTML = r'''<!doctype html>
<html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Search experiment rounds</title>
<style>
*{box-sizing:border-box}body{overflow-wrap:anywhere;margin:0;background:#f4f5f7;color:#172033;font:16px/1.5 system-ui,sans-serif}main{max-width:1500px;margin:auto;padding:24px}h1{margin:0;font-size:28px}h2{font-size:20px;overflow-wrap:anywhere}h3{margin:0;font-size:18px}p{white-space:pre-wrap}select,button,textarea{font:inherit;border:1px solid #aeb8c8;border-radius:6px;padding:8px;background:white}button,summary{cursor:pointer}select{max-width:100%}.toolbar>label{max-width:100%;min-width:0}.toolbar{display:flex;gap:14px;align-items:center;flex-wrap:wrap;margin:16px 0}.wide{width:100%}.columns{display:grid;grid-template-columns:1fr 1fr;gap:20px}.column{min-width:0}article,.panel{background:white;border:1px solid #dde2e9;border-radius:8px;padding:16px;margin:12px 0}.assessment{background:#edf1fa}.winner{border:2px solid #23734d;background:#edf9f0}.note{background:#fff8e5;border-left:4px solid #c18a18}.muted{color:#566277}.badge{font-size:13px;border-radius:4px;background:#e6ecf6;padding:3px 6px}.metrics{background:#e7edf6;padding:12px;border-radius:6px}pre{white-space:pre-wrap;overflow-wrap:anywhere;font-size:12px}.resultHead{display:flex;gap:16px}.posterButton,.noPoster{flex:0 0 90px;width:90px;padding:0;background:#e7edf6;border:0;border-radius:5px;overflow:hidden}.posterButton{cursor:zoom-in}.posterThumb{width:90px;height:135px;object-fit:cover;display:block}.noPoster{height:135px;display:grid;place-items:center;font-size:12px}.resultTitle{min-width:0;overflow-wrap:anywhere}a{color:#1956b8}dialog{border:0;border-radius:10px;background:#111827;color:white;max-width:96vw;max-height:96vh;padding:14px}dialog::backdrop{background:rgba(0,0,0,.85)}#fullPoster{max-width:90vw;max-height:78vh;width:auto;height:auto;object-fit:contain}#closePoster{float:right}body:has(dialog[open]){overflow:hidden}@media(max-width:750px){main{padding:16px}.columns{grid-template-columns:1fr}}
</style>
<main><h1>Search experiment rounds</h1><p class="muted">Measured experiment results. Assistant assessments are provisional and separate from your judgments. Discarded variants remain available for review.</p>
<div id="overall" class="panel"></div><p><a href="loop-findings.md">Findings and limitations</a> · <a href="spend-summary.json">Actual experiment spend</a></p><div class="toolbar"><label>Round <select id="round"></select></label><label><input type="checkbox" id="discarded"> Show discarded variants</label></div><div id="variantNotes"></div>
<label for="request">Request</label><select id="request" class="wide"></select><div class="toolbar"><button id="previous">Previous request</button><button id="next">Next request</button><span id="split" class="badge"></span><span id="progress"></span></div>
<div id="assessment" class="panel assessment"></div><div class="columns"><section class="column"><label>Left variant <select id="left"></select></label><div id="leftResults"></div></section><section class="column"><label>Right variant <select id="right"></select></label><div id="rightResults"></div></section></div>
<div class="panel"><label>Your request preference <select id="preference"></select></label><p><label>Your notes <textarea id="notes" class="wide" rows="3"></textarea></label></p><button id="export">Export your judgments</button><p class="muted">Your judgments stay in this page's memory until exported. Strong = directly satisfies the request; acceptable = reasonably fits; wrong = fails the intent or an exclusion. No automatic quality score is inferred from your judgments.</p></div></main>
<dialog id="posterDialog" aria-labelledby="posterTitle"><button id="closePoster">Close ✕</button><h2 id="posterTitle"></h2><p id="posterStatus" role="status"></p><img id="fullPoster" alt="" hidden></dialog>
<script id="resultsData" type="application/json">__RESULTS_JSON__</script>
<script>
'use strict';
const data=JSON.parse(document.getElementById('resultsData').textContent);for(const r of data.rounds||[])for(const c of r.cases||[])for(const run of Object.values(c.results||{}))if(Array.isArray(run?.top10))run.top10=run.top10.map(t=>({...data.title_sources?.[t.source_ref],...data.evidence_sets?.[t.evidence_ref],...t}));const rounds=[...(data.rounds||[])].reverse(),judgments={},requestJudgments={};let ri=0,ci=0;
const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const pretty=v=>typeof v==='string'?v:JSON.stringify(v,null,2),num=v=>typeof v==='number'&&Number.isFinite(v),ms=v=>num(v)?v.toLocaleString(undefined,{maximumFractionDigits:1})+' ms':'Unknown',cost=v=>num(v)?'$'+v.toFixed(6):'Unknown';
const currentRound=()=>rounds[ri]||{},currentCase=()=>(currentRound().cases||[])[ci],requestKey=()=>JSON.stringify([rounds.length-1-ri,currentCase()?.id??ci]);
const visibleVariants=()=>(currentRound().variants||[]).filter(v=>$('discarded').checked||v.status!=='discarded');
const option=(v,label)=>`<option value="${esc(v)}">${esc(label)}</option>`;
const overall=data.overall||{};if(overall.winner_id)$('overall').classList.add('winner');
$('overall').innerHTML=`<h2>${overall.winner_id?'Selected winner: '+esc(rounds.flatMap(r=>r.variants||[]).find(v=>v.id===overall.winner_id)?.label||overall.winner_id):'No overall winner declared'}</h2><p>${esc(overall.summary||'Overall assessment not supplied.')}</p>${(overall.limitations||[]).length?'<details><summary>Limitations and round-specific provenance</summary><ul>'+overall.limitations.map(s=>'<li>'+esc(s)+'</li>').join('')+'</ul></details>':''}`;
$('round').innerHTML=rounds.map((r,i)=>option(i,r.name||'Unnamed round')).join('');
function setVariants(){const variants=visibleVariants();for(const side of ['left','right']){const previous=$(side).value;$(side).innerHTML=variants.map(v=>option(v.id,`${v.label||v.id} · ${v.status||'status unknown'}`)).join('');$(side).value=variants.some(v=>v.id===previous)?previous:((side==='left'?variants.find(v=>v.status==='winner'):variants.find(v=>/3_1_flash_lite_packing3$/.test(v.id)))?.id||variants[side==='left'?0:Math.min(1,variants.length-1)]?.id||'');}render();}
function setRound(){ci=0;const cases=currentRound().cases||[];$('request').innerHTML=cases.map((c,i)=>option(i,`${i+1}. [${c.split||'split unknown'}] ${c.request||'Request not supplied'}`)).join('');setVariants();}
function metrics(r){const d=r.diagnostics||{};const components=r.components_ms??d.components_ms??d.timings_ms;return `<div class="metrics"><b>${ms(r.wall_ms)}</b> ${/reconstruct|frozen|cache/i.test(String(d.timing_kind||''))?'reconstructed end-to-end time':'end-to-end wall time (see timing provenance)'}<br><b>${cost(r.cost_usd)}</b> measured/estimated cost as reported${components?`<details><summary>Timing components (may overlap)</summary><pre>${esc(pretty(components))}</pre></details>`:''}<small>Missing measurements are unknown, not zero. Components need not sum to wall time.</small></div>${r.error?`<p class="note">Run error: ${esc(pretty(r.error))}</p>`:''}${Object.keys(d).length?`<details><summary>Run diagnostics</summary><pre>${esc(pretty(d))}</pre></details>`:''}`;}
function titleCard(t,i,variant,otherKeys){const key=JSON.stringify([requestKey(),variant,t.key??i]),rating=judgments[key]?.rating||'',poster=typeof t.poster_path==='string'&&/^\/[A-Za-z0-9._-]+$/.test(t.poster_path)?t.poster_path:null;const match=/^(movie|tv):(\d+)$/.exec(t.key||'');const title=match?`<a href="https://www.themoviedb.org/${match[1]}/${match[2]}" target="_blank" rel="noreferrer">${esc(t.title||t.key)}</a>`:esc(t.title||t.key||'Untitled');return `<article><div class="resultHead">${poster?`<button class="posterButton" data-poster="${esc(poster)}" data-title="${esc(t.title)}" aria-label="View original-size poster for ${esc(t.title)}"><img class="posterThumb" src="https://image.tmdb.org/t/p/w185${esc(poster)}" alt="${esc(t.title)} poster" loading="lazy"><span hidden>Poster unavailable</span></button>`:'<div class="noPoster">No poster</div>'}<div class="resultTitle"><h3>${i+1}. ${title}${t.year?' ('+esc(t.year)+')':''}</h3><small>${esc(t.key)}</small> ${otherKeys&&!otherKeys.has(t.key)?'<span class="badge">Only in this top 10</span>':''}</div></div><p>${t.reason?'<small class="muted">Model-generated reason · unverified</small><br>':''}${esc(t.reason||'No model-generated reason supplied.')}</p>${t.evidence!=null?`<details><summary>Match evidence</summary><pre>${esc(pretty(t.evidence))}</pre></details>`:''}${t.essence_text||t.synopsis||t.facet_evidence?`<details><summary>Source description and matching details</summary><p>${esc(t.synopsis||'')}</p><p>${esc(t.essence_text||'')}</p><pre>${esc(pretty({facet_evidence:t.facet_evidence,fingerprint_evidence:t.fingerprint_evidence,avoid_evidence:t.avoid_evidence,contradictions:t.contradictions,unknown:t.unknown}))}</pre></details>`:''}${t.rating!=null?`<p class="muted">Reported rating (not your judgment): ${esc(pretty(t.rating))}</p>`:''}<label>Your judgment <select data-judgment="${esc(key)}" data-title-key="${esc(t.key??i)}" data-variant="${esc(variant)}">${[['','Needs review'],['strong','Strong'],['acceptable','Acceptable'],['wrong','Wrong']].map(([v,l])=>`<option value="${v}" ${rating===v?'selected':''}>${l}</option>`).join('')}</select></label></article>`;}
function render(){const r=currentRound(),c=currentCase(),variants=visibleVariants();$('variantNotes').innerHTML=variants.map(v=>`<details class="panel ${v.status==='winner'?'winner':''}"><summary>${esc(v.label||v.id)} · ${esc(v.status||'status unknown')}</summary><p>${esc(v.reason||'No status rationale supplied.')}</p></details>`).join('')||'<p class="note">No surviving variants in this round. Enable “Show discarded variants” to inspect them.</p>';$('request').value=ci;$('split').textContent=c?.split||'No cases';$('progress').textContent=`${c?ci+1:0} / ${(r.cases||[]).length} requests · ${Object.keys(judgments).length} title judgments`;$('previous').disabled=$('next').disabled=!c;
const a=c?.assessment;$('assessment').innerHTML=a?`<h2>Assistant assessment · ${esc(a.preference||'No preference')}</h2><p>${esc(a.assessment||'Assessment not supplied.')}</p><p><b>Next experiment:</b> ${esc(a.next_experiment||'None supplied.')}</p><small>Independent of your preferences and ratings.</small>`:'<h2>Assistant assessment</h2><p>No assistant assessment supplied for this request.</p>';if(c?.assessments?.length){$('assessment').innerHTML=c.assessments.map(a=>`<details ${a.source?.includes('independent')?'open':''}><summary><b>${esc(a.source||'Assistant assessment')} · ${esc(a.preference||'No preference')}</b></summary>${a.reviewed_input?`<small class="muted">Run reviewed: ${esc(a.reviewed_input.split('/').pop())}</small>`:''}<p>${esc(a.assessment||'No assessment text supplied.')}</p><p><b>Next experiment:</b> ${esc(a.next_experiment||'None supplied.')}</p></details>`).join('')+'<small>Independent assistant opinions; separate from your judgments. Disagreements are retained.</small>';}
for(const side of ['left','right']){const id=$(side).value,result=c?.results?.[id],other=c?.results?.[$(side==='left'?'right':'left').value],otherKeys=Array.isArray(other?.top10)?new Set(other.top10.map(t=>t.key)):null;$(side+'Results').innerHTML=!id?'<p>No visible variant selected.</p>':!result?'<p class="note">No run result supplied for this variant and request.</p>':metrics(result)+(Array.isArray(result.top10)?result.top10.map((t,i)=>titleCard(t,i,id,otherKeys)).join('')||(result.error?'<p>No titles returned by the failed run.</p>':'<p>No titles returned.</p>'):'<p class="note">Top 10 results missing; this is not a measured empty result.</p>');}
const saved=requestJudgments[requestKey()]||{};$('preference').innerHTML=option('','Not reviewed')+option('tie','Tie')+option('neither','Neither')+(r.variants||[]).map(v=>option(v.id,v.label||v.id)).join('');$('preference').value=saved.preference||'';$('notes').value=saved.notes||'';$('preference').disabled=$('notes').disabled=!c;
for(const el of document.querySelectorAll('.posterThumb'))el.onerror=()=>{el.hidden=true;el.nextElementSibling.hidden=false;};
for(const el of document.querySelectorAll('[data-poster]'))el.onclick=()=>openPoster(el.dataset);
for(const el of document.querySelectorAll('[data-judgment]'))el.onchange=()=>{if(el.value)judgments[el.dataset.judgment]={round:r.name,round_index:rounds.length-1-ri,case_id:c.id,request:c.request,variant_id:el.dataset.variant,key:el.dataset.titleKey,rating:el.value};else delete judgments[el.dataset.judgment];render();};}
function openPoster(p){const img=$('fullPoster');img.hidden=true;$('posterStatus').textContent='Loading original-size poster…';$('posterTitle').textContent=p.title;img.alt=p.title+' poster';img.src='https://image.tmdb.org/t/p/original'+p.poster;$('posterDialog').showModal();}
$('fullPoster').onload=()=>{$('fullPoster').hidden=false;$('posterStatus').textContent='Original-size image loaded; scaled to fit your screen.';};$('fullPoster').onerror=()=>{$('fullPoster').hidden=true;$('posterStatus').textContent='Poster could not be loaded.';};$('closePoster').onclick=()=>$('posterDialog').close();$('posterDialog').onclick=e=>{if(e.target===$('posterDialog')){const b=e.target.getBoundingClientRect();if(e.clientX<b.left||e.clientX>b.right||e.clientY<b.top||e.clientY>b.bottom)e.target.close();}};
$('round').onchange=()=>{ri=Number($('round').value);setRound();};$('request').onchange=()=>{ci=Number($('request').value);render();};$('discarded').onchange=setVariants;for(const side of ['left','right'])$(side).onchange=render;for(const [id,delta] of [['previous',-1],['next',1]])$(id).onclick=()=>{const n=(currentRound().cases||[]).length;if(n){ci=(ci+delta+n)%n;render();}};
function saveRequest(){const c=currentCase();if(c)requestJudgments[requestKey()]={round:currentRound().name,round_index:rounds.length-1-ri,case_id:c.id,request:c.request,preference:$('preference').value,notes:$('notes').value};}$('preference').onchange=saveRequest;$('notes').oninput=saveRequest;
$('export').onclick=()=>{const blob=new Blob([JSON.stringify({reviewer:'user',experiment:'iterative-search-review',title_judgments:Object.values(judgments),request_judgments:Object.values(requestJudgments)},null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='search-round-judgments.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};setRound();
</script></html>'''


def render(input_path, output_path):
    """Render results without mutating or inferring measurements/assessments."""
    data = json.loads(Path(input_path).read_text(encoding='utf-8'))
    if not isinstance(data, dict) or not isinstance(data.get('rounds'), list):
        raise ValueError('Expected a JSON object containing a rounds list')
    payload = json.dumps(data, ensure_ascii=False, allow_nan=False).replace('<', '\\u003c').replace('\u2028', '\\u2028').replace('\u2029', '\\u2029')
    output = Path(output_path)
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(HTML.replace('__RESULTS_JSON__', payload), encoding='utf-8')
    return output


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('input_path', type=Path)
    parser.add_argument('output_path', type=Path)
    args = parser.parse_args()
    print(render(args.input_path, args.output_path))
