services:
  arangodb:
    image: arangodb:latest
    restart: unless-stopped
    environment:
#      ARANGO_ROOT_PASSWORD: ${ARANGO_ROOT_PASSWORD}
      ARANGO_NO_AUTH: 1
    ports:
      - "8529:8529"
    volumes:
      - arangodb_data:/var/lib/arangodb3

volumes:
  arangodb_data: